import type { Lesson } from "../types";
import { FOCUS } from "../sources";

export const C1: Lesson = {
  id: "C1",
  code: "C1",
  track: "C",
  kind: "core",
  title: "Algebra · C1 Words → expressions",
  short: "Words → expression",
  minutes: 11,
  piMode: "none",
  prereqs: [],
  citations: [{ file: FOCUS, page: 1, note: "write an expression from words" }],
  intro: "About 11 minutes. Algebra starts as translation: “15 less than h” becomes $h - 15$. We learn which words become which symbols — and the order traps.",
  introBullets: ["Warm-up: order of operations", "Today: turn word phrases into expressions", "Skill path: C1 · one complete teaching loop"],
  recall: [
    {
      id: "C1-r1",
      type: "numeric",
      prompt: "$2 \\times 5 + 3 = \\;?$",
      hints: ["× before +.", "2 × 5 = 10.", "Then + 3."],
      success: "$10 + 3 = 13$.",
      answer: { value: 13 },
      misconceptions: [{ when: 16, say: "You added first. × comes before +." }],
      bridge: "BR-OO",
    },
    {
      id: "C1-r2",
      type: "mcq",
      prompt: "Which operation does “less than” describe?",
      options: ["Addition", "Subtraction", "Multiplication", "Division"],
      correctIndex: 1,
      hints: ["Less means smaller.", "Making a number smaller by an amount.", "Taking away."],
      success: "Subtraction — but watch the **order**: “15 less than h” starts from h.",
    },
  ],
  goal: {
    statement: "Today you will write an algebraic expression from a word phrase.",
    tutor: "A letter stands for a number we don’t know yet. The words tell us what to do with it. Two phrases need special care: “less than” and “divided by” both flip the order you read.",
    formula: "\\text{sum} \\to + \\quad \\text{difference / less than} \\to - \\quad \\text{product / of} \\to \\times \\quad \\text{quotient / shared} \\to \\div",
    formulaPlain: "Sum means add; difference or less than means subtract; product or of means multiply; quotient or shared means divide.",
    visual: { kind: "words-to-symbols" },
    visualTitle: "Visual · words to symbols",
    after: "“15 less than $h$” → start with $h$, take 15 away: $h - 15$. Not $15 - h$.",
  },
  worked: {
    tutor: "I read the phrase twice: once for the operation, once for the order.",
    problem: "Write an expression for: (a) “7 less than $m$”; (b) “the sum of 4 and $3a$, divided by $5b$”.",
    steps: [
      { title: "(a) Operation: less than → subtract. Order: start from m", latex: "m - 7" },
      { title: "(b) Build the sum first", latex: "4 + 3a" },
      { title: "(b) Divide the whole sum — brackets keep it together", latex: "\\frac{4 + 3a}{5b} \\quad\\text{or}\\quad (4 + 3a) \\div 5b" },
    ],
    why: "Brackets (or a fraction bar) show that the **whole** sum is divided — without them only the $3a$ would be.",
    visual: { kind: "words-to-symbols" },
  },
  guided: [
    {
      id: "C1-g1",
      type: "expression",
      prompt: "Write an expression for “15 less than $h$”.",
      hints: ["“Less than” → subtract.", "Which number do you start with? The phrase says less than **h** — so h is the starting amount.", "Write h, then take away 15."],
      success: "$h - 15$. (Writing $-15 + h$ means the same.)",
      answer: { canonical: "h-15", vars: ["h"], acceptedForms: ["h-15", "h - 15", "-15+h"] },
      misconceptions: [{ when: "15-h", say: "Order matters: “15 less than h” starts with h and takes 15 away → $h - 15$." }],
    },
    {
      id: "C1-g2",
      type: "expression",
      prompt: "Write an expression for “twice $y$, plus 9”.",
      hints: ["Twice → × 2.", "$2y$ first.", "Then add 9."],
      success: "$2y + 9$.",
      answer: { canonical: "2y+9", vars: ["y"] },
      misconceptions: [{ when: "2(y+9)", say: "That doubles the 9 as well. The phrase doubles only y, then adds 9." }],
    },
  ],
  independent: [
    {
      id: "C1-i1",
      type: "expression",
      prompt: "Write an expression for “the product of 6 and $t$”.",
      hints: ["Product → multiply.", "6 × t.", "In algebra we write the number first, no × sign."],
      success: "$6t$.",
      answer: { canonical: "6t", vars: ["t"], acceptedForms: ["6t", "6×t", "t×6"] },
    },
    {
      id: "C1-i2",
      type: "expression",
      prompt: "Write an expression for “the sum of $a$ and 8, divided by 3”.",
      hints: ["Sum first: a + 8.", "The **whole** sum is divided by 3.", "Use brackets: (a + 8) ÷ 3, or a fraction."],
      success: "$\\dfrac{a + 8}{3}$, written as $(a+8)/3$.",
      answer: { canonical: "(a+8)/3", vars: ["a"], acceptedForms: ["(a+8)/3", "(a+8)÷3", "(8+a)/3"] },
      misconceptions: [{ when: "a+8/3", say: "Without brackets only the 8 is divided. The phrase divides the whole sum — bracket it." }],
    },
    {
      id: "C1-i3",
      type: "mcq",
      prompt: "Which expression means “4 more than the product of 5 and $k$”?",
      options: ["$5 + 4k$", "$5k + 4$", "$4(5k)$", "$5(k + 4)$"],
      correctIndex: 1,
      hints: ["Product of 5 and k first.", "$5k$.", "Then 4 more → + 4."],
      success: "$5k + 4$.",
    },
  ],
  transfer: [
    {
      id: "C1-t1",
      type: "expression",
      prompt: "A box holds $n$ pens. Four pens are taken out. Write an expression for the number of pens left.",
      hints: ["Start with what was there: n.", "Taking out → subtract.", "n take away 4."],
      success: "$n - 4$.",
      answer: { canonical: "n-4", vars: ["n"] },
      misconceptions: [{ when: "4-n", say: "Start with the pens in the box (n), then remove 4: $n - 4$." }],
    },
  ],
  recap: {
    headline: "Words became algebra",
    tutor: "You translated phrases into symbols and caught the two order traps — that is most of what expression questions test.",
    bullets: ["Sum → +, difference → −, product → ×, quotient → ÷.", "“15 less than $h$” starts from $h$: $h - 15$.", "Divide a **whole** sum → brackets or a fraction bar."],
    nextPath: "Next (C2): collecting like terms — $5h + h - 2h$.",
    collectible: { name: "Cipher bead", glyph: "𝑥", blurb: "Words to symbols." },
  },
};

export const C2: Lesson = {
  id: "C2",
  code: "C2",
  track: "C",
  kind: "core",
  title: "Algebra · C2 Simplify like terms",
  short: "Like terms",
  minutes: 11,
  piMode: "none",
  prereqs: ["C1"],
  citations: [{ file: FOCUS, page: 1, note: "simplify like terms" }],
  intro: "About 11 minutes. Like terms share the same letter; you add or subtract their coefficients. Plain numbers are like terms with each other too.",
  introBullets: ["Warm-up: subtracting past zero", "Today: collect like terms", "Skill path: C2 · one complete teaching loop"],
  recall: [
    {
      id: "C2-r1",
      type: "numeric",
      prompt: "$7 - 9 = \\;?$",
      hints: ["Move 9 left from 7.", "Below zero…", "By 2."],
      success: "$-2$.",
      answer: { value: -2 },
      bridge: "BR-DN",
    },
    {
      id: "C2-r2",
      type: "mcq",
      prompt: "Which pair are **like** terms?",
      options: ["$3a$ and $3b$", "$5x$ and $2x$", "$4$ and $4y$", "$m$ and $m^{2}$"],
      correctIndex: 1,
      hints: ["Like terms share exactly the same letter part.", "Same letter, same power.", "Only the number in front may differ."],
      success: "$5x$ and $2x$ — same letter, so they combine to $7x$.",
    },
  ],
  goal: {
    statement: "Today you will simplify expressions by collecting like terms.",
    tutor: "Think of $h$ as a kind of object. $5h + h - 2h$ is five of them, plus one, minus two — four objects. The letter never changes; only the count does.",
    formula: "5h + h - 2h = (5 + 1 - 2)h = 4h",
    formulaPlain: "Five h plus h minus two h equals four h.",
    visual: { kind: "like-terms" },
    visualTitle: "Visual · sorting terms into groups",
    after: "A lone $h$ is $1h$. Plain numbers only combine with plain numbers.",
  },
  worked: {
    tutor: "I group first, then combine each group — two moves, never mixed.",
    problem: "Simplify (a) $6x + 2x - 3x$; (b) $9 + 4b + 3 + 7b - 5b$.",
    steps: [
      { title: "(a) Coefficients: 6 + 2 − 3", latex: "6x + 2x - 3x = 5x" },
      { title: "(b) Group numbers and b-terms", latex: "(9 + 3) + (4b + 7b - 5b)" },
      { title: "(b) Combine each group", latex: "12 + 6b" },
    ],
    why: "Group like with like, then combine coefficients. Unlike terms stay apart — $12 + 6b$ cannot be squashed into one term.",
    visual: { kind: "like-terms" },
  },
  guided: [
    {
      id: "C2-g1",
      type: "expression",
      prompt: "Simplify $5h + h - 2h$.",
      hints: ["All three are h-terms. A lone h counts as 1h.", "Coefficients: 5 + 1 − 2.", "Attach the h to the result."],
      success: "$5 + 1 - 2 = 4$, so $4h$.",
      answer: { canonical: "4h", vars: ["h"], maxTerms: 1 },
      misconceptions: [{ when: "3h", say: "The lone $h$ is $1h$ — did you count it? 5 + 1 − 2." }, { when: "8h", say: "The $-2h$ is subtracted, not added." }],
      bridge: "BR-DN",
    },
    {
      id: "C2-g2",
      type: "expression",
      prompt: "Simplify $8 + 3a + 2 - a$.",
      hints: ["Two groups: plain numbers (8, 2) and a-terms (3a, −a).", "8 + 2 = 10; 3 − 1 = 2.", "Write both results: number and a-term."],
      success: "$10 + 2a$.",
      answer: { canonical: "10+2a", vars: ["a"], maxTerms: 2 },
      misconceptions: [{ when: "12a", say: "8 and 2 are plain numbers — they don’t join the a-terms. Two separate groups." }, { when: "10+4a", say: "The $-a$ is subtracted: 3 − 1 = 2." }],
      bridge: "BR-DN",
    },
  ],
  independent: [
    {
      id: "C2-i1",
      type: "expression",
      prompt: "Simplify $7p - 2p + p$.",
      hints: ["All p-terms.", "7 − 2 + 1.", "Attach p."],
      success: "$6p$.",
      answer: { canonical: "6p", vars: ["p"], maxTerms: 1 },
      misconceptions: [{ when: "5p", say: "The lone $p$ is $+1p$." }],
    },
    {
      id: "C2-i2",
      type: "expression",
      prompt: "Simplify $12 + 5m + 4 + 9m - 6m$.",
      hints: ["Group: numbers (12, 4) and m-terms (5m, 9m, −6m).", "12 + 4 = 16; 5 + 9 − 6 = 8.", "Two terms in the answer."],
      success: "$16 + 8m$.",
      answer: { canonical: "16+8m", vars: ["m"], maxTerms: 2 },
      misconceptions: [{ when: "24m", say: "Plain numbers and m-terms are different groups — they stay separate." }],
      bridge: "BR-DN",
    },
    {
      id: "C2-i3",
      type: "mcq",
      prompt: "Which expression is **fully** simplified?",
      options: ["$3x + 2x$", "$5x + 4 - 1$", "$5x + 3$", "$x + x + x + 3$"],
      correctIndex: 2,
      hints: ["Look for like terms that could still combine.", "Numbers with numbers, x with x.", "Only one option has nothing left to combine."],
      success: "$5x + 3$ — one x-term, one number, nothing left to collect.",
    },
  ],
  transfer: [
    {
      id: "C2-t1",
      type: "expression",
      prompt: "Simplify $3x + 4y - x + 2y$.",
      hints: ["Two letters → two groups.", "x: 3 − 1 = 2. y: 4 + 2 = 6.", "Write both."],
      success: "$2x + 6y$ — x and y are unlike, so they stay as two terms.",
      answer: { canonical: "2x+6y", vars: ["x", "y"], maxTerms: 2 },
      misconceptions: [{ when: "8xy", say: "x and y are different letters — they cannot be added into one term." }],
    },
  ],
  recap: {
    headline: "Terms sorted, expression simplified",
    tutor: "You grouped before combining every time — that discipline is exactly what keeps longer expressions tidy.",
    bullets: ["Like terms share the same letter; combine their **coefficients**.", "A lone letter has coefficient **1**; the sign travels with the term.", "Plain numbers only combine with plain numbers."],
    nextPath: "Next (C3): expressions from real contexts — 8 crates of $k$ oranges.",
    collectible: { name: "Sorting bead", glyph: "≡", blurb: "Like with like." },
  },
};

export const C3: Lesson = {
  id: "C3",
  code: "C3",
  track: "C",
  kind: "core",
  title: "Algebra · C3 Expressions from context",
  short: "Expression from context",
  minutes: 10,
  piMode: "none",
  prereqs: ["C1"],
  citations: [{ file: FOCUS, page: 1, note: "expression from a real context" }],
  intro: "About 10 minutes. Real situations hide the operation in the story — packets, crates, prices per kilometre. We find it and write the expression.",
  introBullets: ["Warm-up: a word phrase", "Today: write an expression from a real situation", "Skill path: C3 · one complete teaching loop"],
  recall: [
    {
      id: "C3-r1",
      type: "expression",
      prompt: "Write “the product of 4 and $w$”.",
      hints: ["Product → multiply.", "4 × w.", "Number first."],
      success: "$4w$.",
      answer: { canonical: "4w", vars: ["w"] },
    },
  ],
  goal: {
    statement: "Today you will write an expression from a real-world description.",
    tutor: "Ask: how many groups, and how much in each? Repeated equal groups mean multiply. Sharing means divide.",
    formula: "8 \\text{ crates of } k \\text{ oranges} \\to 8k",
    formulaPlain: "Eight crates of k oranges each is eight k.",
    visual: { kind: "words-to-symbols" },
    visualTitle: "Visual · groups and amounts",
    after: "Units help: “R12 per km for $d$ km” → 12 × d rand → $12d$.",
  },
  worked: {
    tutor: "I name the unknown, find the repeated group, then write it.",
    problem: "Each crate holds $k$ oranges. Write an expression for the oranges in 8 crates.",
    steps: [
      { title: "The unknown", latex: "k = \\text{oranges per crate}" },
      { title: "Repeated equal groups → multiply", latex: "8 \\times k" },
      { title: "Algebra style", latex: "8k" },
    ],
    why: "8 crates of k each is k + k + … eight times, which is 8k.",
    visual: { kind: "words-to-symbols" },
  },
  guided: [
    {
      id: "C3-g1",
      type: "expression",
      prompt: "A taxi charges R12 per kilometre. Write an expression for the cost of a trip of $d$ kilometres.",
      hints: ["Each kilometre costs 12; there are d of them.", "12 × d.", "Number first: 12d."],
      success: "$12d$ rand.",
      answer: { canonical: "12d", vars: ["d"] },
      misconceptions: [{ when: "12+d", say: "Each km adds another 12 — that is repeated addition, so multiply: 12d." }],
    },
    {
      id: "C3-g2",
      type: "expression",
      prompt: "$s$ sweets are shared equally among 6 friends. Write an expression for each friend’s share.",
      hints: ["Sharing equally → divide.", "s ÷ 6.", "Written s/6."],
      success: "$\\dfrac{s}{6}$, written $s/6$.",
      answer: { canonical: "s/6", vars: ["s"], acceptedForms: ["s/6", "s÷6"] },
      misconceptions: [{ when: "6/s", say: "The sweets are being shared — s is on top: s ÷ 6." }],
    },
  ],
  independent: [
    {
      id: "C3-i1",
      type: "expression",
      prompt: "A bag of flour weighs $r$ kg. Write an expression for the mass of 5 bags.",
      hints: ["5 equal groups of r.", "5 × r.", "5r."],
      success: "$5r$ kg.",
      answer: { canonical: "5r", vars: ["r"] },
    },
    {
      id: "C3-i2",
      type: "expression",
      prompt: "Thandi has $x$ marbles and buys 9 more. Write an expression for her total.",
      hints: ["Buying more → add.", "x + 9.", "Order doesn’t matter for addition."],
      success: "$x + 9$.",
      answer: { canonical: "x+9", vars: ["x"] },
    },
    {
      id: "C3-i3",
      type: "mcq",
      prompt: "A rope of length $L$ metres is cut into 4 equal pieces. Each piece is…",
      options: ["$L - 4$", "$4L$", "$L / 4$", "$L + 4$"],
      correctIndex: 2,
      hints: ["Equal pieces → sharing.", "Sharing → divide.", "L ÷ 4."],
      success: "$L/4$ — the length shared into four.",
    },
  ],
  transfer: [
    {
      id: "C3-t1",
      type: "expression",
      prompt: "A cinema ticket costs $R t$. Write an expression for the cost of 3 tickets plus a R40 snack.",
      hints: ["3 tickets: 3 × t.", "Then add the snack.", "3t + 40."],
      success: "$3t + 40$ rand.",
      answer: { canonical: "3t+40", vars: ["t"] },
      misconceptions: [{ when: "3(t+40)", say: "The snack is bought once, not three times — add 40 after 3t." }],
    },
  ],
  recap: {
    headline: "Stories became expressions",
    tutor: "You found the hidden operation in each story — groups, sharing, extra — and wrote it cleanly.",
    bullets: ["Repeated equal groups → **multiply** ($8k$).", "Shared equally → **divide** ($s/6$).", "Extra or fewer → **add** or **subtract**."],
    nextPath: "Next (C4): substitute a value and evaluate.",
    collectible: { name: "Story bead", glyph: "✎", blurb: "Context to algebra." },
  },
};

export const C4: Lesson = {
  id: "C4",
  code: "C4",
  track: "C",
  kind: "core",
  title: "Algebra · C4 Substitute and evaluate",
  short: "Substitute",
  minutes: 11,
  piMode: "none",
  prereqs: ["C2"],
  citations: [{ file: FOCUS, page: 2, note: "substitute into an expression" }],
  intro: "About 11 minutes. Substitution swaps a letter for its value, then order of operations does the rest.",
  introBullets: ["Warm-up: order of operations", "Today: substitute a value and evaluate", "Skill path: C4 · one complete teaching loop"],
  recall: [
    {
      id: "C4-r1",
      type: "numeric",
      prompt: "$4 + 6 \\div 2 = \\;?$",
      hints: ["÷ before +.", "6 ÷ 2 = 3.", "4 + 3."],
      success: "$7$.",
      answer: { value: 7 },
      bridge: "BR-OO",
    },
    {
      id: "C4-r2",
      type: "expression",
      prompt: "Simplify $2a + 5a$.",
      hints: ["Like terms.", "2 + 5.", "7a."],
      success: "$7a$.",
      answer: { canonical: "7a", vars: ["a"], maxTerms: 1 },
    },
  ],
  goal: {
    statement: "Today you will substitute a number for a letter and evaluate the expression.",
    tutor: "Write the expression again with brackets where the letter was, drop the number in, then follow the order of operations. Brackets stop $3m$ turning into 35 when $m = 5$.",
    formula: "3m + 4 \\text{ when } m = 5: \\quad 3(5) + 4 = 15 + 4 = 19",
    formulaPlain: "Three m plus four, with m equals five, is three times five plus four, which is nineteen.",
    visual: { kind: "substitute" },
    visualTitle: "Visual · the letter becomes a number",
    after: "$3m$ means $3 \\times m$. With $m = 5$ that is $3 \\times 5$, never “35”.",
  },
  worked: {
    tutor: "Brackets first, then the arithmetic — one line each.",
    problem: "Evaluate $\\dfrac{6y}{3}$ when $y = 4$.",
    steps: [
      { title: "Substitute with brackets", latex: "\\frac{6(4)}{3}" },
      { title: "Top first", latex: "6 \\times 4 = 24" },
      { title: "Divide", latex: "24 \\div 3 = 8" },
    ],
    why: "The fraction bar is a divide sign — work out the top, then divide.",
    visual: { kind: "substitute" },
  },
  guided: [
    {
      id: "C4-g1",
      type: "numeric",
      prompt: "Evaluate $3m + 4$ when $m = 5$.",
      hints: ["Replace m with (5): 3(5) + 4.", "3 × 5 first.", "Then + 4."],
      success: "$3 \\times 5 + 4 = 19$.",
      answer: { value: 19 },
      misconceptions: [{ when: 39, say: "“35” isn’t 3m — $3m$ means $3 \\times 5 = 15$." }, { when: 27, say: "You added before multiplying. 3 × 5 first." }],
      bridge: "BR-OO",
    },
    {
      id: "C4-g2",
      type: "numeric",
      prompt: "Evaluate $2(a + 3)$ when $a = 7$.",
      hints: ["Substitute: 2(7 + 3).", "Brackets first: 7 + 3.", "Then × 2."],
      success: "$2 \\times 10 = 20$.",
      answer: { value: 20 },
      misconceptions: [{ when: 17, say: "Brackets first: 7 + 3 = 10, then double." }],
      bridge: "BR-OO",
    },
  ],
  independent: [
    {
      id: "C4-i1",
      type: "numeric",
      prompt: "Evaluate $5k - 6$ when $k = 4$.",
      hints: ["5(4) − 6.", "5 × 4 = 20.", "20 − 6."],
      success: "$20 - 6 = 14$.",
      answer: { value: 14 },
      misconceptions: [{ when: 48, say: "5k is 5 × 4, not the digits 5 and 4 side by side." }],
    },
    {
      id: "C4-i2",
      type: "numeric",
      prompt: "Evaluate $\\dfrac{x + 9}{4}$ when $x = 11$.",
      hints: ["Top first: 11 + 9.", "That is 20.", "20 ÷ 4."],
      success: "$(11 + 9) \\div 4 = 5$.",
      answer: { value: 5 },
      misconceptions: [{ when: 13.25, say: "The whole top is divided by 4: (11 + 9) ÷ 4, not 11 + 9 ÷ 4." }],
      bridge: "BR-OO",
    },
    {
      id: "C4-i3",
      type: "numeric",
      prompt: "Evaluate $n^{2} + 1$ when $n = 6$.",
      plain: "n squared plus one, with n equals six.",
      hints: ["$n^{2}$ = n × n.", "6 × 6 = 36.", "Then + 1."],
      success: "$36 + 1 = 37$.",
      answer: { value: 37 },
      misconceptions: [{ when: 13, say: "$6^{2}$ is 6 × 6 = 36, not 6 × 2." }],
    },
  ],
  transfer: [
    {
      id: "C4-t1",
      type: "numeric",
      prompt: "A taxi costs $12d + 15$ rand for $d$ kilometres. What does a 6 km trip cost?",
      lead: "cost =",
      unit: "rand",
      hints: ["Substitute d = 6: 12(6) + 15.", "12 × 6 = 72.", "Then + 15."],
      success: "$12 \\times 6 + 15 = 87$ rand.",
      answer: { value: 87 },
      misconceptions: [{ when: 252, say: "You added before multiplying. 12 × 6 first, then + 15." }],
    },
  ],
  recap: {
    headline: "Letters turned into numbers",
    tutor: "Brackets at the substitution step protected you from every classic slip.",
    bullets: ["Substitute with **brackets**: $3m \\to 3(5)$.", "Then follow the order of operations.", "A fraction bar means **divide the whole top**."],
    nextPath: "Next (C5): build an expression from a story, then substitute.",
    collectible: { name: "Key bead", glyph: "⚿", blurb: "Unlocking the value." },
  },
};

export const C5: Lesson = {
  id: "C5",
  code: "C5",
  track: "C",
  kind: "core",
  title: "Algebra · C5 Model, then substitute",
  short: "Model → substitute",
  minutes: 12,
  piMode: "none",
  prereqs: ["C3", "C4"],
  citations: [{ file: FOCUS, page: 2, note: "multi-step: expression from words, then evaluate" }],
  intro: "About 12 minutes. The paper’s hardest algebra items do two things: build an expression from a story, then evaluate it. We do both, in that order.",
  introBullets: ["Warm-up: substitute", "Today: write an expression from a story, then evaluate", "Skill path: C5 · one complete teaching loop"],
  recall: [
    {
      id: "C5-r1",
      type: "numeric",
      prompt: "Evaluate $4w$ when $w = 3$.",
      hints: ["4 × 3.", "Not “43”.", "12."],
      success: "$12$.",
      answer: { value: 12 },
    },
  ],
  goal: {
    statement: "Today you will model a situation with an expression and then evaluate it for a given value.",
    tutor: "Two moves: **model** (write the expression) and **evaluate** (drop in the value). Keep them on separate lines so each can be checked.",
    formula: "\\text{model:}\\; \\frac{x + 14}{4} \\qquad \\text{evaluate } (x = 10):\\; \\frac{24}{4} = 6",
    formulaPlain: "Model: x plus fourteen, over four. Evaluate at x equals ten: twenty-four over four equals six.",
    visual: { kind: "substitute" },
    visualTitle: "Visual · model, then evaluate",
    after: "If the story gives a total and equal parts, subtract what is known, then share the rest.",
  },
  worked: {
    tutor: "Watch the two separate moves — and how the second only starts once the first is written.",
    problem: "A jar has $x$ marbles. 14 more are added, then all are shared equally among 4 friends. (a) Write an expression for each friend’s share. (b) Evaluate it when $x = 10$.",
    steps: [
      { title: "(a) Add first, then share the whole", latex: "\\frac{x + 14}{4}" },
      { title: "(b) Substitute x = 10", latex: "\\frac{10 + 14}{4}" },
      { title: "(b) Top, then divide", latex: "\\frac{24}{4} = 6 \\text{ marbles each}" },
    ],
    why: "Model, then evaluate. The brackets (fraction bar) in the model make the evaluation order automatic.",
    visual: { kind: "substitute" },
  },
  guided: [
    {
      id: "C5-g1",
      type: "expression",
      prompt: "Three siblings’ ages total $15w$. The eldest is $5w$. The other two are the same age. Write an expression for the age of **one** of the younger two.",
      hints: ["Take the eldest away from the total: 15w − 5w.", "That leaves 10w shared between two.", "10w ÷ 2 — simplify it."],
      success: "$(15w - 5w) \\div 2 = 10w \\div 2 = 5w$.",
      answer: { canonical: "5w", vars: ["w"], maxTerms: 1 },
      misconceptions: [{ when: "10w", say: "10w is the two younger siblings **together** — share it between the two." }, { when: "7,5w", say: "Subtract the eldest (5w) before sharing: 15w − 5w = 10w, then halve." }],
    },
    {
      id: "C5-g2",
      type: "numeric",
      prompt: "Using your expression $5w$, find the younger sibling’s age when $w = 3$.",
      lead: "age =",
      hints: ["Substitute w = 3 into 5w.", "5 × 3.", "15."],
      success: "$5 \\times 3 = 15$ years.",
      answer: { value: 15 },
    },
  ],
  independent: [
    {
      id: "C5-i1",
      type: "expression",
      prompt: "A class of $p$ learners is joined by 6 more, then split into 3 equal groups. Write an expression for the size of each group.",
      hints: ["Add first: p + 6.", "Then share the whole into 3.", "Bracket the sum."],
      success: "$(p + 6)/3$.",
      answer: { canonical: "(p+6)/3", vars: ["p"] },
      misconceptions: [{ when: "p+6/3", say: "Bracket the sum — the whole class is split, not just the 6." }],
    },
    {
      id: "C5-i2",
      type: "numeric",
      prompt: "Evaluate $(p + 6)/3$ when $p = 21$.",
      hints: ["Top: 21 + 6.", "27.", "27 ÷ 3."],
      success: "$27 \\div 3 = 9$ learners per group.",
      answer: { value: 9 },
    },
    {
      id: "C5-i3",
      type: "expression",
      prompt: "A rectangle is $3n$ cm long and $n$ cm wide. Write a simplified expression for its perimeter.",
      hints: ["Perimeter = 2 × (length + width).", "2(3n + n) = 2(4n).", "Simplify."],
      success: "$2(3n + n) = 8n$ cm.",
      answer: { canonical: "8n", vars: ["n"], maxTerms: 1 },
      misconceptions: [{ when: "4n", say: "3n + n is only two sides. A rectangle has four — double it." }, { when: "3n^2", say: "That is the area (3n × n). Perimeter adds the sides." }],
    },
  ],
  transfer: [
    {
      id: "C5-t1",
      type: "numeric",
      prompt: "A phone plan costs $R(45 + 2m)$ for $m$ minutes. Find the cost for 30 minutes.",
      lead: "cost =",
      unit: "rand",
      hints: ["Substitute m = 30: 45 + 2(30).", "2 × 30 = 60.", "45 + 60."],
      success: "$45 + 60 = 105$ rand.",
      answer: { value: 105 },
      misconceptions: [{ when: 1410, say: "Multiply 2 × 30 before adding 45." }],
    },
  ],
  recap: {
    headline: "Model and evaluate — the full algebra loop",
    tutor: "You built the expression first and only then substituted — exactly the two-mark structure the papers reward.",
    bullets: ["**Model**: write the expression from the story.", "**Evaluate**: substitute with brackets, then order of operations.", "Total minus known parts, then share → $(15w - 5w)/2$."],
    nextPath: "The algebra track is complete. Perimeter and area (B) reuse this substitution skill.",
    collectible: { name: "Model bead", glyph: "⟐", blurb: "Story → expression → value." },
  },
};

export const ALGEBRA: Lesson[] = [C1, C2, C3, C4, C5];
