import type { Lesson } from "../types";
import { P2024, P2025AUG, FOCUS } from "../sources";

/* Bridges are compact: recall → goal+visual → worked → guided → independent → recap (no transfer). */

export const BR_FD: Lesson = {
  id: "BR-FD",
  code: "BR-FD",
  track: "BR",
  kind: "bridge",
  title: "Bridge · BR-FD Fraction ↔ decimal for π",
  short: "Fraction ↔ decimal for π",
  minutes: 5,
  piMode: "both",
  prereqs: [],
  citations: [{ file: P2024, page: 2, note: "supports π = 3,14 and 22/7 work" }],
  intro: "A short shore-up (~5 minutes): when to keep $\\tfrac{22}{7}$ and cancel, when to multiply by 3,14 — and why both are “π”.",
  introBullets: ["Both forms are the same idea", "Cancel the 7 first with 22/7", "Move the comma with 3,14 × 10, × 100"],
  recall: [
    {
      id: "BRFD-r1",
      type: "numeric",
      prompt: "$22 \\div 7 = 3$ remainder $\\;?$",
      plain: "Twenty-two divided by seven is three with what remainder?",
      hints: ["3 × 7 = 21.", "How far is 21 from 22?", "The leftover is the remainder."],
      success: "$22 = 3 \\times 7 + 1$ — so $\\tfrac{22}{7}$ is “a bit more than 3”, just like 3,14.",
      answer: { value: 1 },
    },
  ],
  goal: {
    statement: "Today you will know when to use $\\tfrac{22}{7}$ (cancel first) and when to use $3{,}14$ (decimal), and see that both are close to π.",
    tutor: "The paper always tells you which form of π to use — the lesson badge does the same. Your only job is to handle each form neatly.",
    formula: "\\pi \\approx \\frac{22}{7} \\approx 3{,}142\\ldots \\qquad \\pi \\approx 3{,}14",
    formulaPlain: "Pi is approximately twenty-two sevenths, which is about 3,142; the paper also uses 3,14.",
    visual: { kind: "fraction-decimal" },
    visualTitle: "Visual · two names for the same number",
    after: "**22/7**: look for a length that is a multiple of 7 and divide it by 7 first. **3,14**: multiplying by 10 or 100 just moves the comma.",
  },
  worked: {
    tutor: "Same diameter, both forms — watch how each stays tidy.",
    problem: "Find $\\pi \\times 14$ using $\\pi = \\tfrac{22}{7}$, and then using $\\pi = 3{,}14$.",
    steps: [
      { title: "With 22/7 — cancel the 7 into 14", latex: "\\frac{22}{7} \\times 14 = 22 \\times 2 = 44" },
      { title: "With 3,14 — multiply the decimal", latex: "3{,}14 \\times 14 = 31{,}4 + 12{,}56 = 43{,}96" },
      { title: "Compare", note: "44 and 43,96 — nearly the same, because both stand for π. The paper picks one; you follow." },
    ],
    why: "Both answers are “right for their π”. Never mix forms inside one question.",
    visual: { kind: "fraction-decimal" },
  },
  guided: [
    {
      id: "BRFD-g1",
      type: "numeric",
      prompt: "$\\tfrac{22}{7} \\times 7 = \\;?$",
      hints: ["The 7s cancel.", "What is left on top?", "Just the 22."],
      success: "$22$ — multiplying by 7 undoes the ÷ 7.",
      answer: { value: 22 },
    },
    {
      id: "BRFD-g2",
      type: "numeric",
      prompt: "$2 \\times 3{,}14 = \\;?$",
      hints: ["Double 3 and double 0,14 separately.", "6 and 0,28.", "Put them together."],
      success: "$6{,}28$ — this product appears inside every $2\\pi r$ with 3,14.",
      answer: { value: 6.28 },
    },
  ],
  independent: [
    {
      id: "BRFD-i1",
      type: "numeric",
      prompt: "$\\tfrac{22}{7} \\times 28 = \\;?$",
      hints: ["28 is a multiple of 7.", "28 ÷ 7 = 4.", "22 × 4."],
      success: "$22 \\times 4 = 88$.",
      answer: { value: 88 },
    },
    {
      id: "BRFD-i2",
      type: "numeric",
      prompt: "$3{,}14 \\times 100 = \\;?$",
      hints: ["× 100 moves the comma two places to the right.", "3,14 → 31,4 → …", "One more place."],
      success: "$314$ — the comma moved two places.",
      answer: { value: 314 },
    },
    {
      id: "BRFD-i3",
      type: "mcq",
      prompt: "As a decimal, $\\tfrac{22}{7}$ is closest to…",
      options: ["2,27", "3,14", "7,22", "22,7"],
      correctIndex: 1,
      hints: ["22 ÷ 7 is “3 and a bit”.", "Which option is just over 3?", "The same value as the decimal π."],
      success: "3,14 — that is exactly why the two forms are interchangeable names for π.",
    },
  ],
  transfer: [],
  recap: {
    headline: "Two doors, one π",
    tutor: "You can now handle either form the paper hands you.",
    bullets: ["$\\tfrac{22}{7}$: **cancel the 7** into a multiple of 7 first.", "$3{,}14$: × 10 or × 100 just **moves the comma**.", "Both mean π — never mix them in one question."],
    collectible: { name: "Bridge plank", glyph: "═", blurb: "Fraction and decimal, joined." },
  },
};

export const BR_FR: Lesson = {
  id: "BR-FR",
  code: "BR-FR",
  track: "BR",
  kind: "bridge",
  title: "Bridge · BR-FR Formula recall",
  short: "Formula recall",
  minutes: 5,
  piMode: "none",
  prereqs: [],
  citations: [{ file: P2025AUG, page: 2, note: "square perimeter, rectangle area, circle formula recall" }],
  intro: "A short shore-up (~5 minutes): the perimeter and area formulas for square, rectangle and triangle — and how to tell them from the circle ones.",
  introBullets: ["Perimeter adds edges; area covers space", "Square, rectangle, triangle formulas", "Circle: C uses d or 2r; A uses r²"],
  recall: [
    {
      id: "BRFR-r1",
      type: "mcq",
      prompt: "Which of these is measured in **square** units?",
      options: ["Perimeter", "Area", "Circumference", "Diameter"],
      correctIndex: 1,
      hints: ["Three of these are lengths.", "Which one covers space?", "The space inside a shape."],
      success: "Area — cm², m². The others are lengths.",
    },
  ],
  goal: {
    statement: "Today you will recall the perimeter and area formulas for a square, rectangle and triangle.",
    tutor: "Perimeter walks the edge; area paints the inside. Hold that picture and the formulas stop being a list to memorise.",
    formula: "P_{\\square} = 4s \\quad A_{\\square} = s^{2} \\quad P_{\\text{rect}} = 2(l + b) \\quad A_{\\text{rect}} = l \\times b \\quad A_{\\triangle} = \\tfrac{1}{2} b h",
    formulaPlain: "Square: perimeter 4 s, area s squared. Rectangle: perimeter 2 times (l plus b), area l times b. Triangle area: half base times height.",
    visual: { kind: "formula-cards" },
    visualTitle: "Visual · formula cards",
    after: "The circle pair: $C = \\pi d$ (a length) and $A = \\pi r^{2}$ (an area). Squared → area, every time.",
  },
  worked: {
    tutor: "One rectangle, both measurements — so the difference is visible.",
    problem: "A rectangle is $8\\,\\text{cm}$ long and $5\\,\\text{cm}$ wide. Find its perimeter and area.",
    steps: [
      { title: "Perimeter — walk the edge", latex: "P = 2(8 + 5) = 2 \\times 13 = 26\\,\\text{cm}" },
      { title: "Area — cover the inside", latex: "A = 8 \\times 5 = 40\\,\\text{cm}^{2}" },
    ],
    why: "Perimeter adds lengths (cm). Area multiplies two lengths (cm²).",
    visual: { kind: "rectangle", w: "8 cm", h: "5 cm", shade: true },
  },
  guided: [
    {
      id: "BRFR-g1",
      type: "numeric",
      prompt: "A square has side $9\\,\\text{cm}$. Perimeter?",
      lead: "P =",
      unit: "cm",
      hints: ["Four equal sides.", "4 × 9.", "Walk all four edges."],
      success: "$P = 4 \\times 9 = 36$ cm.",
      answer: { value: 36 },
      misconceptions: [{ when: 81, say: "9 × 9 is the area. Perimeter adds the four sides: 4 × 9." }],
    },
    {
      id: "BRFR-g2",
      type: "numeric",
      prompt: "A triangle has base $10\\,\\text{cm}$ and height $4\\,\\text{cm}$. Area?",
      lead: "A =",
      unit: "cm²",
      hints: ["Triangle area is half of base × height.", "10 × 4 = 40.", "Halve it."],
      success: "$A = \\tfrac{1}{2} \\times 10 \\times 4 = 20$ cm².",
      answer: { value: 20 },
      misconceptions: [{ when: 40, say: "That is base × height — a rectangle. A triangle is half of that." }],
    },
  ],
  independent: [
    {
      id: "BRFR-i1",
      type: "mcq",
      prompt: "Which formula gives the **area** of a rectangle?",
      options: ["$2(l + b)$", "$l \\times b$", "$4l$", "$\\tfrac{1}{2} l b$"],
      correctIndex: 1,
      hints: ["Area multiplies two lengths.", "Length times breadth.", "No halving — that is for triangles."],
      success: "$A = l \\times b$.",
    },
    {
      id: "BRFR-i2",
      type: "numeric",
      prompt: "A rectangle is $12\\,\\text{cm}$ by $3\\,\\text{cm}$. Perimeter?",
      lead: "P =",
      unit: "cm",
      hints: ["Two lengths and two breadths.", "2 × (12 + 3).", "2 × 15."],
      success: "$P = 2(12 + 3) = 30$ cm.",
      answer: { value: 30 },
      misconceptions: [{ when: 36, say: "12 × 3 is the area. Perimeter adds the edges." }],
    },
    {
      id: "BRFR-i3",
      type: "mcq",
      prompt: "Which circle formula gives an **area**?",
      options: ["$C = \\pi d$", "$C = 2\\pi r$", "$A = \\pi r^{2}$", "$d = 2r$"],
      correctIndex: 2,
      hints: ["Area needs something squared.", "Look for the little 2 on the r.", "$r^{2}$."],
      success: "$A = \\pi r^{2}$ — the squared radius makes it an area.",
    },
  ],
  transfer: [],
  recap: {
    headline: "Formulas back in the toolkit",
    tutor: "Perimeter walks, area paints — and squared always means area.",
    bullets: ["Square: $P = 4s$, $A = s^{2}$. Rectangle: $P = 2(l+b)$, $A = l \\times b$.", "Triangle: $A = \\tfrac{1}{2} b h$.", "Circle: $C = \\pi d$ (length), $A = \\pi r^{2}$ (area)."],
    collectible: { name: "Bridge plank", glyph: "═", blurb: "Formulas recalled." },
  },
};

export const BR_OO: Lesson = {
  id: "BR-OO",
  code: "BR-OO",
  track: "BR",
  kind: "bridge",
  title: "Bridge · BR-OO Order of operations",
  short: "Order of operations",
  minutes: 5,
  piMode: "none",
  prereqs: [],
  citations: [{ file: FOCUS, page: 2, note: "supports substitution and multi-step evaluation" }],
  intro: "A short shore-up (~5 minutes): brackets, then powers, then × and ÷, then + and −. Substitution questions depend on it.",
  introBullets: ["Brackets first", "Powers next, then × ÷, then + −", "Left to right within a level"],
  recall: [
    {
      id: "BROO-r1",
      type: "numeric",
      prompt: "$3 + 4 \\times 2 = \\;?$",
      hints: ["Which comes first — the + or the ×?", "Multiplication before addition.", "4 × 2 first, then add 3."],
      success: "$3 + 8 = 11$. Multiply before you add.",
      answer: { value: 11 },
      misconceptions: [{ when: 14, say: "You added first. × happens before +: 4 × 2 = 8, then 3 + 8." }],
    },
  ],
  goal: {
    statement: "Today you will evaluate a numeric expression in the right order: brackets → powers → × ÷ → + −.",
    tutor: "Without an agreed order, one expression could mean two things. The order is the agreement — and it is exactly what a substituted formula relies on.",
    formula: "(\\;) \\;\\to\\; x^{2} \\;\\to\\; \\times \\div \\;\\to\\; + -",
    formulaPlain: "Brackets, then powers, then multiplication and division, then addition and subtraction.",
    visual: { kind: "order-ops" },
    visualTitle: "Visual · the order ladder",
    after: "Within the same level, work **left to right**.",
  },
  worked: {
    tutor: "I’ll write one line per step so the order is visible.",
    problem: "Evaluate $2 \\times (3 + 5) - 4$.",
    steps: [
      { title: "Brackets first", latex: "3 + 5 = 8" },
      { title: "Multiply", latex: "2 \\times 8 = 16" },
      { title: "Subtract", latex: "16 - 4 = 12" },
    ],
    why: "Brackets, then ×, then −. Each line changes one thing.",
    visual: { kind: "order-ops" },
  },
  guided: [
    {
      id: "BROO-g1",
      type: "numeric",
      prompt: "$10 - 2 \\times 3 = \\;?$",
      hints: ["× before −.", "2 × 3 = 6.", "10 − 6."],
      success: "$10 - 6 = 4$.",
      answer: { value: 4 },
      misconceptions: [{ when: 24, say: "You subtracted first. Do 2 × 3 before the −." }],
    },
    {
      id: "BROO-g2",
      type: "numeric",
      prompt: "$18 \\div (2 + 4) = \\;?$",
      hints: ["Brackets first.", "2 + 4 = 6.", "18 ÷ 6."],
      success: "$18 \\div 6 = 3$.",
      answer: { value: 3 },
      misconceptions: [{ when: 13, say: "You divided first. Brackets come before ÷: 2 + 4 = 6." }],
    },
  ],
  independent: [
    {
      id: "BROO-i1",
      type: "numeric",
      prompt: "$4 + 6 \\div 2 = \\;?$",
      hints: ["÷ before +.", "6 ÷ 2 = 3.", "4 + 3."],
      success: "$4 + 3 = 7$.",
      answer: { value: 7 },
      misconceptions: [{ when: 5, say: "You added first. ÷ comes before +." }],
    },
    {
      id: "BROO-i2",
      type: "numeric",
      prompt: "$5 \\times 2^{2} = \\;?$",
      plain: "Five times two squared.",
      hints: ["Powers before ×.", "$2^{2} = 4$.", "5 × 4."],
      success: "$5 \\times 4 = 20$.",
      answer: { value: 20 },
      misconceptions: [{ when: 100, say: "You multiplied first, then squared. Powers come before ×: $2^{2} = 4$." }],
    },
    {
      id: "BROO-i3",
      type: "mcq",
      prompt: "In $7 + 3 \\times (6 - 2)$, what do you work out **first**?",
      options: ["$7 + 3$", "$3 \\times 6$", "$6 - 2$", "$7 + 3 \\times 6$"],
      correctIndex: 2,
      hints: ["Look for brackets.", "Whatever is inside them goes first.", "6 − 2."],
      success: "$6 - 2 = 4$ first, then $3 \\times 4$, then $+ 7$ — total 19.",
    },
  ],
  transfer: [],
  recap: {
    headline: "The order is yours",
    tutor: "Brackets, powers, × ÷, + − — one line per step and nothing slips.",
    bullets: ["**Brackets** first, then **powers**.", "Then **× and ÷**, then **+ and −**.", "Same level → left to right."],
    collectible: { name: "Bridge plank", glyph: "═", blurb: "Order of operations." },
  },
};

export const BR_DN: Lesson = {
  id: "BR-DN",
  code: "BR-DN",
  track: "BR",
  kind: "bridge",
  title: "Bridge · BR-DN Directed numbers in like terms",
  short: "Directed numbers",
  minutes: 5,
  piMode: "none",
  prereqs: [],
  citations: [{ file: FOCUS, page: 1, note: "supports simplifying like terms with subtraction" }],
  intro: "A short shore-up (~5 minutes): when collecting like terms, the sign in front of a term travels with it.",
  introBullets: ["The sign belongs to the term after it", "Adding and subtracting on a number line", "Coefficients combine like plain numbers"],
  recall: [
    {
      id: "BRDN-r1",
      type: "numeric",
      prompt: "$7 - 9 = \\;?$",
      hints: ["Start at 7 on a number line and move 9 to the left.", "Past zero…", "How far below zero do you land?"],
      success: "$7 - 9 = -2$. Going below zero is allowed.",
      answer: { value: -2 },
      misconceptions: [{ when: 2, say: "Close — but 7 − 9 goes **below** zero: −2." }],
    },
  ],
  goal: {
    statement: "Today you will add and subtract coefficients, including when the result is negative.",
    tutor: "$5h - 7h$ is just $5 - 7$ with an $h$ attached. Keep the sign glued to the number that follows it.",
    formula: "5h - 7h = (5 - 7)h = -2h",
    formulaPlain: "Five h minus seven h equals negative two h.",
    visual: { kind: "number-line" },
    visualTitle: "Visual · coefficients on a number line",
    after: "Read $-3a$ as “negative three a”, not “minus three, then a”.",
  },
  worked: {
    tutor: "I’ll pull the coefficients out, combine them like plain numbers, then put the letter back.",
    problem: "Simplify $4b - 9b + 2b$.",
    steps: [
      { title: "Coefficients only", latex: "4 - 9 + 2" },
      { title: "Left to right", latex: "4 - 9 = -5, \\quad -5 + 2 = -3" },
      { title: "Put the letter back", latex: "-3b" },
    ],
    why: "Like terms combine by their coefficients. Signs travel with the number after them.",
    visual: { kind: "number-line" },
  },
  guided: [
    {
      id: "BRDN-g1",
      type: "numeric",
      prompt: "$3 - 8 = \\;?$",
      hints: ["Start at 3, move 8 left.", "3 to 0 is 3 steps; 5 more steps…", "Below zero by 5."],
      success: "$-5$.",
      answer: { value: -5 },
    },
    {
      id: "BRDN-g2",
      type: "expression",
      prompt: "Simplify $2x - 6x$.",
      hints: ["Coefficients: 2 − 6.", "That is −4.", "Put the x back."],
      success: "$2x - 6x = -4x$.",
      answer: { canonical: "-4x", vars: ["x"], maxTerms: 1 },
      misconceptions: [{ when: "4x", say: "2 − 6 is **negative** 4 — the sign matters." }],
    },
  ],
  independent: [
    {
      id: "BRDN-i1",
      type: "expression",
      prompt: "Simplify $5h - 8h + h$.",
      hints: ["Coefficients: 5 − 8 + 1 (a lone h is 1h).", "5 − 8 = −3, then −3 + 1.", "Attach the h."],
      success: "$5 - 8 + 1 = -2$, so $-2h$.",
      answer: { canonical: "-2h", vars: ["h"], maxTerms: 1 },
      misconceptions: [{ when: "-3h", say: "Don’t forget the lone $h$ — it is $+1h$." }, { when: "2h", say: "5 − 8 + 1 is **negative** 2." }],
    },
    {
      id: "BRDN-i2",
      type: "expression",
      prompt: "Simplify $6 - 10 + 3k$.",
      hints: ["Only the plain numbers combine: 6 − 10.", "That is −4. The $3k$ has no partner.", "Write both terms."],
      success: "$-4 + 3k$ (or $3k - 4$).",
      answer: { canonical: "3k-4", vars: ["k"], maxTerms: 2 },
      misconceptions: [{ when: "-k", say: "6, 10 and 3k are not all like terms — only 6 and 10 combine." }],
    },
  ],
  transfer: [],
  recap: {
    headline: "Signs stay attached",
    tutor: "Negative coefficients hold no fear now — they are just numbers below zero with a letter beside them.",
    bullets: ["The sign belongs to the term **after** it.", "Combine coefficients like plain numbers: $5 - 7 = -2$.", "A lone letter has coefficient **1**."],
    collectible: { name: "Bridge plank", glyph: "═", blurb: "Directed numbers." },
  },
};

export const BRIDGES: Lesson[] = [BR_FD, BR_FR, BR_OO, BR_DN];
