import type { Lesson } from "../types";
import { P2024, P2025AUG, FOCUS } from "../sources";

/* ------------------------------------------------------------------ */
/* A1 — Circle parts                                                   */
/* ------------------------------------------------------------------ */

export const A1: Lesson = {
  id: "A1",
  code: "A1",
  track: "A",
  kind: "core",
  title: "Circles · A1 Parts of a circle",
  short: "Circle parts",
  minutes: 10,
  piMode: "none",
  prereqs: [],
  citations: [
    { file: P2024, page: 2, note: "circle vocabulary" },
    { file: FOCUS, page: 3, note: "naming radius, diameter, chord" },
  ],
  intro:
    "About 10 minutes. We’ll meet the words that every circle question uses — centre, radius, diameter, chord and circumference — so the later formulas make sense instead of being memorised.",
  introBullets: [
    "Warm-up: the special point every circle is built around",
    "Today: name each part of a circle from a diagram",
    "Skill path: A1 · one complete teaching loop",
  ],
  recall: [
    {
      id: "A1-r1",
      type: "mcq",
      prompt: "Every point on a circle is the same distance from one special point. What is that point called?",
      options: ["The corner", "The centre", "The edge", "The side"],
      correctIndex: 1,
      hints: [
        "Think about drawing a circle with a compass — where does the sharp point sit?",
        "The compass point stays still in the middle while the pencil travels around.",
        "The word for the middle point of a circle starts with “c” and is not “corner” — circles have no corners.",
      ],
      success: "Yes — the **centre**. Every part of a circle is measured from here.",
    },
    {
      id: "A1-r2",
      type: "numeric",
      prompt: "Quick number warm-up: what is half of 18?",
      hints: ["Halving means sharing into two equal parts.", "Split 18 into 10 + 8 and halve each part.", "Half of 10 is 5, half of 8 is 4. Add them."],
      success: "Half of 18 is **9**. Halving and doubling are the two moves radius and diameter need.",
      answer: { value: 9 },
    },
  ],
  goal: {
    statement: "Today you will name the parts of a circle: centre, radius, diameter, chord and circumference.",
    tutor:
      "Every circle question starts by reading the picture. Once you can point to each part and say its name, the formulas later are just sentences about these parts.",
    formula: "\\text{radius} \\to \\text{centre to edge} \\qquad \\text{diameter} \\to \\text{edge to edge through } O",
    formulaPlain: "A radius runs from the centre to the edge. A diameter runs edge to edge through the centre.",
    visual: {
      kind: "circle",
      radius: true,
      diameter: true,
      chord: true,
      arc: true,
      centre: true,
      labels: { r: "radius", d: "diameter", C: "circumference", chord: "chord" },
    },
    visualTitle: "Visual · the parts, labelled",
    after:
      "A **chord** joins two points on the circle. The **diameter** is a special chord — the longest one — because it passes through the centre.",
  },
  worked: {
    tutor:
      "Watch how I read a labelled circle. I ask one question of each line: does it touch the centre, and does it go all the way across?",
    problem:
      "In a circle with centre $O$, line $AC$ passes through $O$ from edge to edge. Line $OD$ runs from $O$ to the edge. Line $BC$ joins two points on the edge but misses $O$. Name each line.",
    steps: [
      { title: "Line AC — edge to edge, through the centre", latex: "AC = \\text{diameter}", note: "It crosses the whole circle through O." },
      { title: "Line OD — centre to edge", latex: "OD = \\text{radius}", note: "One end sits on the centre." },
      { title: "Line BC — edge to edge, misses the centre", latex: "BC = \\text{chord}", note: "Two edge points joined, but not through O." },
    ],
    why: "Ask two questions of any line: Does it touch the centre? Does it go all the way across? The answers name the part.",
    visual: { kind: "circle", radius: true, diameter: true, chord: true, centre: true, labels: { r: "OD", d: "AC", chord: "BC" } },
  },
  guided: [
    {
      id: "A1-g1",
      type: "hotspot",
      diagram: "circle-parts",
      prompt: "Click the line that is a **radius**.",
      plain: "Choose the segment that runs from the centre O to the edge of the circle.",
      correctTarget: "radius",
      hints: [
        "A radius has one end exactly on the centre O.",
        "Two of the lines touch the centre. Only one of them stops at the centre instead of crossing it.",
        "Look for the shorter line that starts at O and ends on the circle.",
      ],
      success: "That’s the **radius** — centre to edge. Notice it is exactly half of the diameter.",
      misconceptions: [
        { when: "diameter", say: "That one goes right through the centre to the other side — that makes it a diameter (two radii long)." },
        { when: "chord", say: "That line misses the centre altogether, so it’s a chord." },
      ],
    },
    {
      id: "A1-g2",
      type: "mcq",
      prompt: "A line joins two points on the circle but does **not** pass through the centre. What is it called?",
      options: ["A radius", "A diameter", "A chord", "The circumference"],
      correctIndex: 2,
      hints: [
        "Radius and diameter both involve the centre. This line avoids it.",
        "The circumference is the whole curved edge, not a straight line.",
        "The straight line that skips the centre is a chord — like the string of a bow.",
      ],
      success: "A **chord**. If it happened to pass through the centre, it would be promoted to diameter.",
    },
  ],
  independent: [
    {
      id: "A1-i1",
      type: "hotspot",
      diagram: "circle-parts",
      prompt: "Click the line that is a **chord**.",
      plain: "Choose the segment that joins two edge points without passing through the centre.",
      correctTarget: "chord",
      hints: [
        "A chord touches the edge twice and the centre never.",
        "Rule out any line touching O.",
        "The remaining edge-to-edge line is the chord.",
      ],
      success: "Correct — a **chord** joins two edge points and misses the centre.",
      misconceptions: [{ when: "diameter", say: "That line does pass through the centre — it is a diameter, the longest chord of all." }],
    },
    {
      id: "A1-i2",
      type: "mcq",
      prompt: "Which of these is the longest straight line you can draw inside a circle?",
      options: ["A radius", "A chord that misses the centre", "A diameter", "They are all the same length"],
      correctIndex: 2,
      hints: [
        "Imagine sliding a chord towards the centre — does it get longer or shorter?",
        "A chord grows as it approaches the centre.",
        "The chord that passes through the centre is longest — it has a special name.",
      ],
      success: "The **diameter** — the chord through the centre. Every other chord is shorter.",
    },
    {
      id: "A1-i3",
      type: "mcq",
      prompt: "The distance all the way around the edge of a circle is called its…",
      options: ["Diameter", "Circumference", "Chord", "Radius"],
      correctIndex: 1,
      hints: [
        "Three of the options are straight lines. One is a distance around a curve.",
        "It’s the circle’s version of perimeter.",
        "Circum- means “around”.",
      ],
      success: "**Circumference** — the perimeter of a circle. We’ll measure it in A3 and A4.",
    },
  ],
  transfer: [
    {
      id: "A1-t1",
      type: "mcq",
      prompt: "A round garden table has a metal rod fixed from its exact middle out to the rim. Which circle part is the rod?",
      options: ["A chord", "The circumference", "A diameter", "A radius"],
      correctIndex: 3,
      hints: [
        "Where does the rod start? Where does it end?",
        "Middle to rim is centre to edge.",
        "Centre to edge is the definition of one particular part.",
      ],
      success: "A **radius** — centre to edge. A rod from rim to rim through the middle would be a diameter.",
    },
  ],
  recap: {
    headline: "You lit the first lantern",
    tutor: "You can now read a circle diagram the way a tutor does — by asking which lines touch the centre and which cross the whole circle.",
    bullets: [
      "A **radius** runs from the centre to the edge; a **diameter** crosses edge to edge through the centre.",
      "A **chord** joins two edge points without the centre — the diameter is the longest chord.",
      "The **circumference** is the distance around the circle.",
    ],
    nextPath: "Next on the path (A2): the diameter is exactly two radii — $d = 2r$.",
    collectible: { name: "Compass bead", glyph: "◎", blurb: "For naming every part of the circle." },
  },
};

/* ------------------------------------------------------------------ */
/* A2 — Diameter = 2 × radius                                          */
/* ------------------------------------------------------------------ */

export const A2: Lesson = {
  id: "A2",
  code: "A2",
  track: "A",
  kind: "core",
  title: "Circles · A2 Radius ↔ diameter",
  short: "Radius ↔ diameter",
  minutes: 10,
  piMode: "none",
  prereqs: ["A1"],
  citations: [
    { file: FOCUS, page: 3, note: "diameter from radius" },
    { file: P2024, page: 2, note: "radius ↔ diameter" },
  ],
  intro: "About 10 minutes. One idea, both directions: the diameter is two radii long, so doubling and halving move you between them.",
  introBullets: ["Warm-up: spot the radius; double a number", "Today: switch between radius and diameter", "Skill path: A2 · one complete teaching loop"],
  recall: [
    {
      id: "A2-r1",
      type: "hotspot",
      diagram: "circle-parts",
      prompt: "Click the **radius**.",
      plain: "Choose the segment from the centre O to the edge.",
      correctTarget: "radius",
      hints: ["Centre to edge.", "One end must sit on O.", "It stops at the centre rather than crossing it."],
      success: "Radius found — centre to edge.",
    },
    {
      id: "A2-r2",
      type: "numeric",
      prompt: "Double 9.",
      hints: ["Doubling means adding a number to itself.", "9 + 9.", "Count on from 9 by 9."],
      success: "9 doubled is **18**. Doubling a radius gives a diameter.",
      answer: { value: 18 },
    },
  ],
  goal: {
    statement: "Today you will switch between radius and diameter using $d = 2r$ and $r = \\tfrac{d}{2}$.",
    tutor:
      "Two radii placed end to end, both starting at the centre, make one diameter. That single picture gives both formulas.",
    formula: "d = 2r \\qquad r = \\frac{d}{2}",
    formulaPlain: "Diameter equals two times radius. Radius equals diameter divided by two.",
    visual: { kind: "circle", radius: true, diameter: true, centre: true, labels: { r: "r", d: "d = 2r" } },
    visualTitle: "Visual · two radii make a diameter",
    after: "Given a radius → **double** it. Given a diameter → **halve** it. Say which one the question gave you before you calculate.",
  },
  worked: {
    tutor: "I’ll say out loud which length I was given, then choose double or halve. That one sentence prevents most slips later.",
    problem: "A circle has radius $r = 9\\,\\text{cm}$. Find its diameter.",
    steps: [
      { title: "Name what you were given", latex: "r = 9\\,\\text{cm}", note: "Radius given → I need to double." },
      { title: "Write the formula", latex: "d = 2r" },
      { title: "Substitute and calculate", latex: "d = 2 \\times 9 = 18\\,\\text{cm}" },
    ],
    why: "Radius given → double. Diameter given → halve. The formula d = 2r says exactly that.",
    visual: { kind: "circle", radius: true, diameter: true, centre: true, labels: { r: "9 cm", d: "d = ?" } },
  },
  guided: [
    {
      id: "A2-g1",
      type: "numeric",
      prompt: "A circle has radius $r = 6{,}5\\,\\text{cm}$. Find the diameter.",
      plain: "Radius is six comma five centimetres. Find the diameter.",
      lead: "d =",
      unit: "cm",
      hints: [
        "You were given the radius. Double or halve?",
        "d = 2 × r. Write d = 2 × 6,5.",
        "Double 6, then double 0,5, and add the two parts. Include cm.",
      ],
      success: "$d = 2 \\times 6{,}5 = 13$ cm. Doubling a half gives a whole number — neat.",
      answer: { value: 13 },
      misconceptions: [{ when: 3.25, say: "You halved — but a radius was given, so the diameter is bigger: double it." }],
    },
    {
      id: "A2-g2",
      type: "numeric",
      prompt: "A circle has diameter $d = 30\\,\\text{mm}$. Find the radius.",
      lead: "r =",
      unit: "mm",
      hints: ["This time the diameter is given. Double or halve?", "r = d ÷ 2. Write r = 30 ÷ 2.", "Share 30 into two equal parts. Include mm."],
      success: "$r = 30 \\div 2 = 15$ mm. Diameter given → halve.",
      answer: { value: 15 },
      misconceptions: [{ when: 60, say: "You doubled — but you were given the diameter, which is already the long one. Halve it." }],
    },
  ],
  independent: [
    {
      id: "A2-i1",
      type: "numeric",
      prompt: "Radius $r = 11\\,\\text{cm}$. Diameter?",
      lead: "d =",
      unit: "cm",
      hints: ["Radius given.", "d = 2r.", "Double 11."],
      success: "$d = 2 \\times 11 = 22$ cm.",
      answer: { value: 22 },
      misconceptions: [{ when: 5.5, say: "That’s halving. Radius given → double." }],
    },
    {
      id: "A2-i2",
      type: "numeric",
      prompt: "Diameter $d = 17\\,\\text{cm}$. Radius?",
      lead: "r =",
      unit: "cm",
      hints: ["Diameter given.", "r = d ÷ 2 = 17 ÷ 2.", "Half of 16 is 8; half of the remaining 1 is 0,5. A comma decimal is fine."],
      success: "$r = 17 \\div 2 = 8{,}5$ cm. Comma decimals are exactly how SA papers write it.",
      answer: { value: 8.5 },
      misconceptions: [{ when: 34, say: "That’s doubling. Diameter given → halve." }],
    },
    {
      id: "A2-i3",
      type: "mcq",
      prompt: "A circular pond has radius $4\\,\\text{m}$. How wide is it from one edge to the opposite edge through the middle?",
      options: ["2 m", "4 m", "8 m", "16 m"],
      correctIndex: 2,
      hints: ["Edge to edge through the middle is the diameter.", "d = 2r with r = 4.", "Double 4."],
      success: "8 m — the diameter is twice the 4 m radius.",
      misconceptions: [{ when: "3", say: "16 would be 4 × 4 — that’s squaring, which belongs to area, not diameter." }],
    },
  ],
  transfer: [
    {
      id: "A2-t1",
      type: "numeric",
      prompt: "A bicycle wheel has diameter $70\\,\\text{cm}$. Each spoke runs from the centre hub to the rim. How long is one spoke?",
      lead: "spoke =",
      unit: "cm",
      hints: ["A spoke is centre to rim — which circle part is that?", "A spoke is a radius, and you were given the diameter.", "r = d ÷ 2 = 70 ÷ 2."],
      success: "One spoke is a radius: $70 \\div 2 = 35$ cm.",
      answer: { value: 35 },
      misconceptions: [{ when: 140, say: "A spoke is centre-to-rim — a radius — so it’s shorter than the diameter, not longer." }],
    },
  ],
  recap: {
    headline: "Two radii, one diameter — yours now",
    tutor: "You decided double-or-halve by naming what you were given first. Keep that habit; it protects every circumference and area calculation ahead.",
    bullets: ["$d = 2r$ — radius given, double it.", "$r = \\tfrac{d}{2}$ — diameter given, halve it.", "Say which length you were given **before** you calculate."],
    nextPath: "Next (A3): what circumference means — and why it is a little more than three diameters.",
    collectible: { name: "Twin bead", glyph: "∞", blurb: "Two radii, one diameter." },
  },
};

/* ------------------------------------------------------------------ */
/* A3 — Meaning of circumference                                       */
/* ------------------------------------------------------------------ */

export const A3: Lesson = {
  id: "A3",
  code: "A3",
  track: "A",
  kind: "core",
  title: "Circles · A3 What circumference means",
  short: "Circumference meaning",
  minutes: 10,
  piMode: "none",
  prereqs: ["A1"],
  citations: [{ file: P2024, page: 2, note: "meaning of circumference" }],
  intro: "About 10 minutes. Before any formula, we make sure “circumference” means something you can picture — and estimate.",
  introBullets: ["Warm-up: radius and diameter", "Today: explain circumference and estimate it as “a bit more than 3 diameters”", "Skill path: A3 · one complete teaching loop"],
  recall: [
    {
      id: "A3-r1",
      type: "mcq",
      prompt: "If a circle has radius $4$, its diameter is…",
      options: ["2", "4", "8", "12"],
      correctIndex: 2,
      hints: ["Diameter is two radii.", "d = 2r.", "Double 4."],
      success: "8 — two radii make a diameter.",
    },
    {
      id: "A3-r2",
      type: "hotspot",
      diagram: "circle-parts",
      prompt: "Click the **diameter**.",
      plain: "Choose the line that crosses the whole circle through the centre.",
      correctTarget: "diameter",
      hints: ["Edge to edge, through O.", "It is the longest line in the picture.", "Both ends on the circle, middle on the centre."],
      success: "Diameter — the full width through the centre.",
    },
  ],
  goal: {
    statement: "Today you will explain what circumference is and estimate it: a little more than three diameters.",
    tutor:
      "Circumference is the distance **around** the circle — its perimeter. If you cut the rim and laid it flat, it would be just over three diameters long. That “just over three” is the number we call π.",
    formula: "C \\approx 3 \\times d \\quad (\\text{a little more})",
    formulaPlain: "Circumference is approximately three times the diameter, and slightly more.",
    visual: { kind: "diameters-around" },
    visualTitle: "Visual · the diameter wrapped around the rim",
    after: "Three diameters almost wrap the circle; a small gap is left. That gap is why π is 3,14…, not exactly 3.",
  },
  worked: {
    tutor: "Estimating first is a tutor habit — it tells you what size of answer to expect before the exact formula.",
    problem: "A circular pond has diameter $2\\,\\text{m}$. Roughly how far is one walk around its edge?",
    steps: [
      { title: "Name the distance", latex: "\\text{around the edge} = \\text{circumference}" },
      { title: "Estimate with three diameters", latex: "C \\approx 3 \\times 2 = 6\\,\\text{m}" },
      { title: "Say what the estimate means", note: "A little more than 6 m — the exact value uses π, which is a bit bigger than 3." },
    ],
    why: "Circumference is always about three diameters. If your exact answer later is nowhere near 3 × d, a slip has crept in.",
    visual: { kind: "circle", diameter: true, arc: true, centre: true, labels: { d: "2 m", C: "about 6 m" } },
  },
  guided: [
    {
      id: "A3-g1",
      type: "mcq",
      prompt: "Which sentence describes **circumference**?",
      options: ["The distance across the circle through the middle", "The distance all the way around the circle", "The space inside the circle", "Half of the diameter"],
      correctIndex: 1,
      hints: ["Across is diameter; inside is area.", "Circum- means around.", "Think of the rim of a wheel."],
      success: "The distance **around** — the circle’s perimeter.",
      misconceptions: [
        { when: "0", say: "Across through the middle is the diameter — a straight line. Circumference is the curved distance around." },
        { when: "2", say: "The space inside is the area. Circumference is a length around the outside." },
      ],
    },
    {
      id: "A3-g2",
      type: "numeric",
      prompt: "A circle has diameter $5\\,\\text{cm}$. Estimate its circumference using “about 3 diameters”.",
      lead: "C ≈",
      unit: "cm",
      hints: ["How many diameters roughly fit around a circle?", "About 3. So multiply the diameter by 3.", "3 × 5, then say “a little more”."],
      success: "About $3 \\times 5 = 15$ cm (the exact value, 15,7 cm, is a little more — as expected).",
      answer: { value: 15, range: [15, 16] },
    },
  ],
  independent: [
    {
      id: "A3-i1",
      type: "mcq",
      prompt: "On a bicycle wheel, which measurement is the circumference?",
      options: ["The length of one spoke", "The width of the hub", "The distance once around the tyre", "The distance across the wheel"],
      correctIndex: 2,
      hints: ["Circumference is a distance around.", "A spoke is a radius; across is a diameter.", "The tyre’s edge is the rim of the circle."],
      success: "Once around the tyre — that is the circumference. One wheel turn moves the bike forward by exactly this distance.",
    },
    {
      id: "A3-i2",
      type: "numeric",
      prompt: "Roughly how many diameters fit around the circumference of any circle?",
      lead: "about",
      hints: ["It is the same for every circle.", "It is a whole number plus a little bit.", "Just over three."],
      success: "About **3** (3,14… to be exact — that is π).",
      answer: { value: 3, range: [3, 3.2] },
    },
    {
      id: "A3-i3",
      type: "numeric",
      prompt: "A round clock face has diameter $10\\,\\text{cm}$. Estimate the distance around its edge.",
      lead: "C ≈",
      unit: "cm",
      hints: ["Circumference ≈ 3 × diameter.", "3 × 10.", "Then add “a little more” — anywhere from 30 to 32 is a fair estimate."],
      success: "About $3 \\times 10 = 30$ cm; exactly 31,4 cm — the estimate and the exact answer agree.",
      answer: { value: 30, range: [30, 32] },
    },
  ],
  transfer: [
    {
      id: "A3-t1",
      type: "numeric",
      prompt: "You want a ribbon to go once around a round cake tin of diameter $20\\,\\text{cm}$. Estimate the ribbon length.",
      lead: "about",
      unit: "cm",
      hints: ["Once around = circumference.", "≈ 3 × d = 3 × 20.", "60 and a little more — anything from 60 to 63 is a sensible estimate."],
      success: "About $3 \\times 20 = 60$ cm, a little more to be safe (exactly 62,8 cm).",
      answer: { value: 60, range: [60, 63] },
    },
  ],
  recap: {
    headline: "Circumference has a picture now",
    tutor: "You can explain circumference and estimate it before touching a formula — that estimate will catch slips in every lesson ahead.",
    bullets: ["Circumference = the distance **around** a circle (its perimeter).", "It is a little more than **3 diameters**.", "That “little more than 3” is $\\pi \\approx 3{,}14$."],
    nextPath: "Next (A4): the exact formula, $C = \\pi d$, with $\\pi = 3{,}14$.",
    collectible: { name: "Rim bead", glyph: "○", blurb: "Three diameters and a little more." },
  },
};

/* ------------------------------------------------------------------ */
/* A4 — Circumference with π = 3,14 (starter lesson)                   */
/* ------------------------------------------------------------------ */

export const A4: Lesson = {
  id: "A4",
  code: "A4",
  track: "A",
  kind: "core",
  title: "Circles · A4 Circumference",
  short: "Circumference · 3,14",
  minutes: 12,
  piMode: "3,14",
  prereqs: [],
  citations: [
    { file: P2024, page: 2, note: "circumference from diameter, π = 3,14" },
    { file: FOCUS, page: 3, note: "circumference from diameter" },
  ],
  intro:
    "About 10–12 minutes. We’ll warm up, see a clear picture, work an example together, then try a few with me beside you. Soft reward when the beacon brightens.",
  introBullets: ["Warm-up: connect radius and diameter", "Today: find circumference with $\\pi = 3{,}14$", "Skill path: A4 · one complete teaching loop"],
  recall: [
    {
      id: "A4-r1",
      type: "numeric",
      prompt: "A circle has radius $r = 6\\,\\text{cm}$. What is the diameter?",
      plain: "Diameter is twice the radius — the full width through the centre.",
      lead: "d =",
      unit: "cm",
      hints: ["The diameter goes all the way across through the centre — two radii end to end.", "d = 2 × r. Substitute r = 6.", "Double 6. Include cm."],
      success: "$d = 2r = 12$ cm. Radius given → double.",
      answer: { value: 12 },
      misconceptions: [{ when: 3, say: "You halved — but a radius was given. The diameter is the longer one: double it." }],
    },
    {
      id: "A4-r2",
      type: "numeric",
      prompt: "Decimal warm-up: $2 \\times 3{,}14 = \\;?$",
      plain: "Two times three comma one four.",
      hints: ["Double 3, then double 0,14.", "2 × 3 = 6 and 2 × 0,14 = 0,28.", "Put the two parts back together."],
      success: "$2 \\times 3{,}14 = 6{,}28$. You’ll see this exact product inside $2\\pi r$.",
      answer: { value: 6.28 },
      bridge: "BR-FD",
    },
  ],
  goal: {
    statement: "Today you will find the circumference of a circle using $\\pi = 3{,}14$.",
    tutor:
      "Here’s what we’re aiming for. Circumference is the distance **around** the circle — the path a beacon-light would travel if it ran the rim once.",
    formula: "C = \\pi d \\qquad\\text{or}\\qquad C = 2\\pi r",
    formulaPlain: "Circumference equals pi times diameter, or two times pi times radius.",
    visual: { kind: "circle", radius: true, diameter: true, arc: true, centre: true, labels: { r: "r", d: "d = 2r", C: "circumference C" } },
    visualTitle: "Visual · circle parts",
    after: "Same idea either way: if you know the **diameter**, use $\\pi d$; if you know the **radius**, use $2\\pi r$.",
  },
  worked: {
    tutor: "Watch the choice on each line: formula, substitution, calculation. I’ll keep the working visible so nothing feels like a magic jump.",
    problem: "A circular bridge ring has diameter $d = 10\\,\\text{cm}$. Find the circumference. Use $\\pi = 3{,}14$.",
    steps: [
      { title: "Write the formula", latex: "C = \\pi d", note: "The diameter is given, so πd is the direct route." },
      { title: "Substitute", latex: "C = 3{,}14 \\times 10" },
      { title: "Calculate", latex: "C = 31{,}4\\,\\text{cm}", note: "Check: r = 5, so C = 2πr = 2 × 3,14 × 5 = 31,4 cm — same." },
    ],
    why: "The diameter is given, so $C = \\pi d$ is the direct route. Estimate check: 3 × 10 = 30, and 31,4 is a little more. ✓",
    visual: { kind: "circle", diameter: true, arc: true, centre: true, labels: { d: "d = 10 cm", C: "C = ?" } },
  },
  guided: [
    {
      id: "A4-g1",
      type: "numeric",
      prompt: "Radius $r = 7\\,\\text{cm}$. Find $C$ using $\\pi = 3{,}14$ and $C = 2\\pi r$.",
      plain: "Twice pi times the radius.",
      lead: "C =",
      unit: "cm",
      hints: [
        "The question gives a radius. Which displayed formula begins with radius: $C = \\pi d$ or $C = 2\\pi r$?",
        "Write $C = 2 \\times 3{,}14 \\times 7$. Do $2 \\times 3{,}14$ first — you already know it from the warm-up.",
        "Now multiply that result by 7: six times 7, then 0,28 times 7, and add. Include cm.",
      ],
      success: "$2 \\times 3{,}14 = 6{,}28$, then $6{,}28 \\times 7 = 43{,}96$ cm. That’s the circumference — distance around.",
      answer: { value: 43.96 },
      misconceptions: [
        { when: 21.98, say: "That’s $\\pi \\times r$ — only half of the circumference. With a radius you need $2\\pi r$: double it." },
        { when: 87.92, say: "You doubled twice. $2 \\times 3{,}14 \\times 7$ needs just one doubling." },
      ],
      bridge: "BR-FD",
    },
    {
      id: "A4-g2",
      type: "numeric",
      prompt: "Diameter $d = 20\\,\\text{cm}$. Find $C$ using $\\pi = 3{,}14$.",
      plain: "Pi times the diameter.",
      lead: "C =",
      unit: "cm",
      hints: ["This time the diameter is given. Which formula uses d directly?", "$C = \\pi d = 3{,}14 \\times 20$.", "Multiply 3,14 by 2, then by 10 (move the comma one place). Include cm."],
      success: "$C = 3{,}14 \\times 20 = 62{,}8$ cm. Estimate check: 3 × 20 = 60, a little more. ✓",
      answer: { value: 62.8 },
      misconceptions: [
        { when: 125.6, say: "You used $2\\pi d$ — the 2 belongs with the **radius**. With a diameter, $C = \\pi d$." },
        { when: 31.4, say: "That’s half. Did you halve 20 first? With a diameter, use $\\pi d$ directly — no halving." },
      ],
      bridge: "BR-FD",
    },
  ],
  independent: [
    {
      id: "A4-i1",
      type: "numeric",
      prompt: "Diameter $d = 12\\,\\text{cm}$. Find $C$ using $\\pi = 3{,}14$ and $C = \\pi d$.",
      plain: "Pi times twelve.",
      lead: "C =",
      unit: "cm",
      hints: ["Diameter given → $\\pi d$.", "$C = 3{,}14 \\times 12$.", "Split 12 into 10 + 2: multiply 3,14 by each and add."],
      success: "$3{,}14 \\times 12 = 31{,}4 + 6{,}28 = 37{,}68$ cm.",
      answer: { value: 37.68 },
      misconceptions: [
        { when: 75.36, say: "You doubled the diameter. The 2 in $2\\pi r$ goes with the radius — with a diameter use $C = \\pi d$." },
        { when: 18.84, say: "That’s half the circumference — you halved 12 first, then forgot the 2 in $2\\pi r$. Simpler: $\\pi d$." },
      ],
      bridge: "BR-FD",
    },
    {
      id: "A4-i2",
      type: "numeric",
      prompt: "A circle has diameter $50\\,\\text{cm}$. Find its circumference. Use $\\pi = 3{,}14$.",
      plain: "Pi times fifty.",
      lead: "C =",
      unit: "cm",
      hints: ["Which length were you given — radius or diameter?", "$C = \\pi d = 3{,}14 \\times 50$.", "3,14 × 100 would be 314; you need half of that. Include cm."],
      success: "$C = 3{,}14 \\times 50 = 157$ cm. Estimate: 3 × 50 = 150, a little more. ✓",
      answer: { value: 157 },
      misconceptions: [
        { when: 314, say: "You doubled the diameter — that is $2\\pi d$. The 2 belongs with the **radius**; with a diameter use $C = \\pi d$." },
        { when: 78.5, say: "You halved 50 to get the radius — fine — but then you need $2\\pi r$, which brings you back to $\\pi d$. Simpler: $3{,}14 \\times 50$." },
      ],
      bridge: "BR-FD",
    },
    {
      id: "A4-i3",
      type: "mcq",
      prompt: "You know the radius $r$. Which formula gives the circumference?",
      options: ["$C = \\pi r$", "$C = 2\\pi r$", "$C = \\pi r^{2}$", "$C = 2r$"],
      correctIndex: 1,
      hints: ["Circumference is π times the diameter — and the diameter is two radii.", "Replace $d$ in $\\pi d$ with $2r$.", "$\\pi \\times 2r$ rearranged."],
      success: "$C = 2\\pi r$ — because $d = 2r$, so $\\pi d = \\pi \\times 2r$.",
      misconceptions: [
        { when: "2", say: "$\\pi r^{2}$ is the **area** formula — square units, the space inside." },
        { when: "3", say: "$2r$ is just the diameter — you still need to multiply by π." },
      ],
    },
    {
      id: "A4-i4",
      type: "expression",
      prompt: "A circle has diameter $d$. Using $\\pi = 3{,}14$, write an expression for its circumference.",
      plain: "Write the circumference in terms of d, with pi replaced by three comma one four.",
      hints: ["Start from $C = \\pi d$.", "Replace π with the declared value 3,14.", "Write 3,14 next to d — that means 3,14 × d."],
      success: "$C = 3{,}14d$ — that is $\\pi d$ with the declared value of π.",
      answer: { canonical: "3,14d", vars: ["d"], acceptedForms: ["3,14d", "3.14d", "3,14×d", "d×3,14", "3,14*d"] },
      misconceptions: [{ when: "6,28d", say: "That is $2\\pi d$ — the 2 belongs with the radius. With a diameter, no doubling." }],
    },
  ],
  transfer: [
    {
      id: "A4-t1",
      type: "numeric",
      prompt: "A circular light-garden has radius $5\\,\\text{m}$. A path runs once around its edge. How long is the path? Use $\\pi = 3{,}14$.",
      plain: "Find the circumference of a circle with radius five metres.",
      lead: "C =",
      unit: "m",
      hints: ["Once around the edge is the circumference. You were given a radius.", "$C = 2\\pi r = 2 \\times 3{,}14 \\times 5$.", "2 × 5 = 10 first, then 3,14 × 10 (move the comma one place). Include m."],
      success: "$C = 2 \\times 3{,}14 \\times 5 = 31{,}4$ m — same as a circle with diameter 10.",
      answer: { value: 31.4 },
      misconceptions: [{ when: 15.7, say: "That’s $\\pi \\times r$. A radius needs $2\\pi r$ — double it." }],
      visual: { kind: "garden", label: "r = 5 m" },
    },
  ],
  recap: {
    headline: "You restored a bead of light",
    tutor: "You didn’t just reach an answer — you chose the formula from the length you were given. Here’s the compact version to keep.",
    bullets: [
      "Circumference is the distance **around** a circle.",
      "With diameter: $C = \\pi d$. With radius: $C = 2\\pi r$.",
      "This lesson used $\\pi = 3{,}14$ (comma decimal). You’ll also meet $\\tfrac{22}{7}$.",
    ],
    nextPath: "Up next (A5): circumference with $\\pi = \\tfrac{22}{7}$ — cancel the 7 first and the numbers stay friendly.",
    collectible: { name: "Lumen bead", glyph: "✦", blurb: "A quiet marker of this path restored." },
  },
  alt: {
    title: "Another way to see it",
    tutor: "Same bridge ring ($d = 10$ cm). If diameter feels noisy, start from radius — two doors into one room. Pick the door that clicks.",
    pathA: { title: "Path A · from diameter", body: "$C = \\pi d = 3{,}14 \\times 10 = 31{,}4$" },
    pathB: { title: "Path B · from radius", body: "Half of 10 is $r = 5$. $C = 2\\pi r = 2 \\times 3{,}14 \\times 5 = 31{,}4$ — same circumference." },
  },
};

/* ------------------------------------------------------------------ */
/* A5 — Circumference with π = 22/7                                    */
/* ------------------------------------------------------------------ */

export const A5: Lesson = {
  id: "A5",
  code: "A5",
  track: "A",
  kind: "core",
  title: "Circles · A5 Circumference with 22/7",
  short: "Circumference · 22/7",
  minutes: 12,
  piMode: "22/7",
  prereqs: ["A4"],
  citations: [
    { file: P2024, page: 4, note: "circumference × laps, π = 22/7" },
    { file: FOCUS, page: 4, note: "one wheel rotation, π = 22/7" },
  ],
  intro: "About 12 minutes. Same formulas as A4, new π: with 22/7 you cancel the 7 **before** multiplying, so the arithmetic stays whole-number friendly.",
  introBullets: ["Warm-up: doubling a radius; 22/7 × 7", "Today: circumference with $\\pi = \\tfrac{22}{7}$", "Skill path: A5 · one complete teaching loop"],
  recall: [
    {
      id: "A5-r1",
      type: "numeric",
      prompt: "Radius $r = 14\\,\\text{cm}$. Diameter?",
      lead: "d =",
      unit: "cm",
      hints: ["Radius given.", "d = 2r.", "Double 14."],
      success: "$d = 28$ cm.",
      answer: { value: 28 },
    },
    {
      id: "A5-r2",
      type: "numeric",
      prompt: "Fraction warm-up: $\\tfrac{22}{7} \\times 7 = \\;?$",
      plain: "Twenty-two sevenths times seven.",
      hints: ["Multiplying by 7 undoes dividing by 7.", "The 7 on the bottom cancels the 7 you multiply by.", "What is left on top?"],
      success: "$\\tfrac{22}{7} \\times 7 = 22$. The sevens cancel — that is the whole trick of 22/7.",
      answer: { value: 22 },
      bridge: "BR-FD",
    },
  ],
  goal: {
    statement: "Today you will find circumference with $\\pi = \\tfrac{22}{7}$ by cancelling the 7 before you multiply.",
    tutor: "22/7 looks awkward until you notice the papers always pair it with a length that is a multiple of 7. Divide that length by 7 first, and the rest is a small times-table fact.",
    formula: "C = \\pi d = \\frac{22}{7} \\times d \\qquad C = 2\\pi r = 2 \\times \\frac{22}{7} \\times r",
    formulaPlain: "Circumference equals twenty-two sevenths times diameter, or two times twenty-two sevenths times radius.",
    visual: { kind: "wheel", label: "r = 14 cm" },
    visualTitle: "Visual · a wheel turning once",
    after: "One full turn of a wheel moves it forward exactly one **circumference**. That is why wheel questions are circumference questions.",
  },
  worked: {
    tutor: "Watch where I cancel. I never multiply 22 by 14 — I let the 7 do its job first.",
    problem: "A wheel has radius $14\\,\\text{cm}$. How far does it travel in one full rotation? Use $\\pi = \\tfrac{22}{7}$.",
    steps: [
      { title: "Write the formula", latex: "C = 2\\pi r", note: "Radius given." },
      { title: "Substitute", latex: "C = 2 \\times \\frac{22}{7} \\times 14" },
      { title: "Cancel the 7 into the 14", latex: "= 2 \\times 22 \\times 2", note: "14 ÷ 7 = 2." },
      { title: "Calculate", latex: "C = 88\\,\\text{cm}", note: "Estimate: 3 × 28 = 84, a little more. ✓" },
    ],
    why: "Cancel first, multiply second. 14 ÷ 7 = 2 turns a messy fraction into 2 × 22 × 2.",
    visual: { kind: "wheel", label: "r = 14 cm" },
  },
  guided: [
    {
      id: "A5-g1",
      type: "numeric",
      prompt: "Diameter $d = 21\\,\\text{cm}$. Find $C$ using $\\pi = \\tfrac{22}{7}$.",
      plain: "Twenty-two sevenths times twenty-one.",
      lead: "C =",
      unit: "cm",
      hints: ["Diameter given → $C = \\pi d = \\tfrac{22}{7} \\times 21$.", "Divide 21 by 7 first. What do you get?", "21 ÷ 7 = 3, so the answer is 22 × 3. Include cm."],
      success: "$\\tfrac{22}{7} \\times 21 = 22 \\times 3 = 66$ cm.",
      answer: { value: 66 },
      misconceptions: [
        { when: 132, say: "You doubled — but the diameter was given. $\\pi d$ has no 2." },
        { when: 33, say: "Check the cancel: 21 ÷ 7 = 3, then 22 × 3." },
      ],
      bridge: "BR-FD",
    },
    {
      id: "A5-g2",
      type: "numeric",
      prompt: "Radius $r = 7\\,\\text{cm}$. Find $C$ using $\\pi = \\tfrac{22}{7}$.",
      lead: "C =",
      unit: "cm",
      hints: ["Radius given → $C = 2\\pi r$.", "$2 \\times \\tfrac{22}{7} \\times 7$ — the 7s cancel.", "That leaves 2 × 22."],
      success: "$2 \\times \\tfrac{22}{7} \\times 7 = 2 \\times 22 = 44$ cm.",
      answer: { value: 44 },
      misconceptions: [{ when: 22, say: "That is $\\pi \\times r$ — half. A radius needs $2\\pi r$." }],
      bridge: "BR-FD",
    },
  ],
  independent: [
    {
      id: "A5-i1",
      type: "numeric",
      prompt: "Diameter $d = 35\\,\\text{cm}$. Find $C$. Use $\\pi = \\tfrac{22}{7}$.",
      lead: "C =",
      unit: "cm",
      hints: ["Diameter → $\\pi d$.", "35 ÷ 7 = ?", "Then 22 × 5."],
      success: "$\\tfrac{22}{7} \\times 35 = 22 \\times 5 = 110$ cm.",
      answer: { value: 110 },
      misconceptions: [{ when: 220, say: "Doubled — the diameter was given, so no 2." }, { when: 55, say: "Half — check 35 ÷ 7 = 5, then 22 × 5." }],
      bridge: "BR-FD",
    },
    {
      id: "A5-i2",
      type: "numeric",
      prompt: "Radius $r = 21\\,\\text{cm}$. Find $C$. Use $\\pi = \\tfrac{22}{7}$.",
      lead: "C =",
      unit: "cm",
      hints: ["Radius → $2\\pi r$.", "$2 \\times \\tfrac{22}{7} \\times 21$; cancel 21 ÷ 7 = 3.", "2 × 22 × 3."],
      success: "$2 \\times 22 \\times 3 = 132$ cm.",
      answer: { value: 132 },
      misconceptions: [{ when: 66, say: "That is $\\pi r$ — you need $2\\pi r$ for a radius." }],
      bridge: "BR-FD",
    },
    {
      id: "A5-i3",
      type: "mcq",
      prompt: "Why is $\\pi = \\tfrac{22}{7}$ handy when the radius is $14$?",
      options: ["Because 22 is even", "Because 14 is a multiple of 7, so the 7 cancels", "Because 14 is bigger than 7", "It isn’t — 3,14 is always easier"],
      correctIndex: 1,
      hints: ["Look at the 7 on the bottom of the fraction.", "What happens to 14 ÷ 7?", "A whole-number answer means the fraction disappears."],
      success: "14 ÷ 7 = 2, so $\\tfrac{22}{7} \\times 14 = 44$ with no decimals at all.",
    },
  ],
  transfer: [
    {
      id: "A5-t1",
      type: "numeric",
      prompt: "A circular running track has radius $35\\,\\text{m}$. How far does a runner go in **two** laps? Use $\\pi = \\tfrac{22}{7}$.",
      plain: "Find twice the circumference of a circle with radius thirty-five metres.",
      lead: "distance =",
      unit: "m",
      hints: ["One lap is one circumference. Radius given.", "$C = 2 \\times \\tfrac{22}{7} \\times 35$; cancel 35 ÷ 7 = 5 → 2 × 22 × 5.", "That is one lap. The question asks for two — double it."],
      success: "One lap $= 2 \\times 22 \\times 5 = 220$ m; two laps $= 440$ m.",
      answer: { value: 440 },
      misconceptions: [{ when: 220, say: "That is one lap — the runner does two. Double it." }, { when: 110, say: "That is $\\pi r$ for one lap. Use $2\\pi r$, then two laps." }],
    },
  ],
  recap: {
    headline: "The fraction bent to your will",
    tutor: "You cancelled before multiplying every time — that is exactly how the papers expect 22/7 to be handled.",
    bullets: ["With $\\pi = \\tfrac{22}{7}$, **cancel the 7** into the length first.", "Then $C = \\pi d$ or $C = 2\\pi r$ becomes a small times-table fact.", "Laps and wheel turns are **circumference** questions."],
    nextPath: "Next (A6): area, $A = \\pi r^{2}$ — the space inside, in square units.",
    collectible: { name: "Sevens bead", glyph: "⁷", blurb: "Cancel first, multiply second." },
  },
};

/* ------------------------------------------------------------------ */
/* A6 — Area of a circle                                               */
/* ------------------------------------------------------------------ */

export const A6: Lesson = {
  id: "A6",
  code: "A6",
  track: "A",
  kind: "core",
  title: "Circles · A6 Area of a circle",
  short: "Area · πr²",
  minutes: 12,
  piMode: "both",
  prereqs: ["A4"],
  citations: [
    { file: P2024, page: 2, note: "area from radius, π = 22/7" },
    { file: P2025AUG, page: 2, note: "recognising A = π × r × r" },
  ],
  intro: "About 12 minutes. Area is the space **inside** — measured in square units. The formula $A = \\pi r^{2}$ always wants the radius, squared.",
  introBullets: ["Warm-up: halving a diameter; squaring", "Today: area of a circle with 3,14 and with 22/7", "Skill path: A6 · one complete teaching loop"],
  recall: [
    {
      id: "A6-r1",
      type: "numeric",
      prompt: "Diameter $d = 16\\,\\text{cm}$. Radius?",
      lead: "r =",
      unit: "cm",
      hints: ["Diameter given → halve.", "r = 16 ÷ 2.", "Half of 16."],
      success: "$r = 8$ cm.",
      answer: { value: 8 },
    },
    {
      id: "A6-r2",
      type: "numeric",
      prompt: "Squaring warm-up: $5^{2} = \\;?$",
      plain: "Five squared.",
      hints: ["Squaring means multiplying a number by itself.", "5 × 5.", "Not 5 × 2 — that would be doubling."],
      success: "$5^{2} = 5 \\times 5 = 25$. Squaring is not doubling — that distinction runs this whole lesson.",
      answer: { value: 25 },
      misconceptions: [{ when: 10, say: "5 × 2 is doubling. Squaring is 5 × 5." }],
      bridge: "BR-FR",
    },
  ],
  goal: {
    statement: "Today you will find the area of a circle using $A = \\pi r^{2}$ — with $\\pi = 3{,}14$ and with $\\pi = \\tfrac{22}{7}$.",
    tutor: "Area is the space inside — how much paint covers the disc. A square drawn on the radius fits inside the circle a little more than three times. That “a little more than three” is π again.",
    formula: "A = \\pi r^{2} = \\pi \\times r \\times r",
    formulaPlain: "Area equals pi times radius times radius, in square units.",
    visual: { kind: "circle", radius: true, centre: true, shadeArea: true, labels: { r: "r" } },
    visualTitle: "Visual · the space inside",
    after: "Two habits: always use the **radius** (halve a diameter first), and **square** it (r × r, not 2 × r). Units come out squared: cm².",
  },
  worked: {
    tutor: "I’ll square the radius as its own line before π touches it — that keeps “squared” and “doubled” from blurring together.",
    problem: "A circle has radius $r = 5\\,\\text{cm}$. Find its area. Use $\\pi = 3{,}14$.",
    steps: [
      { title: "Write the formula", latex: "A = \\pi r^{2}" },
      { title: "Square the radius first", latex: "r^{2} = 5 \\times 5 = 25" },
      { title: "Substitute and calculate", latex: "A = 3{,}14 \\times 25 = 78{,}5\\,\\text{cm}^{2}", note: "3 × 25 = 75 and 0,14 × 25 = 3,5." },
    ],
    why: "Square first, then multiply by π. And write cm² — area is always in square units, even when a paper forgets the little 2.",
    visual: { kind: "circle", radius: true, centre: true, shadeArea: true, labels: { r: "5 cm" } },
  },
  guided: [
    {
      id: "A6-g1",
      type: "numeric",
      prompt: "Radius $r = 10\\,\\text{cm}$. Find the area. Use $\\pi = 3{,}14$.",
      lead: "A =",
      unit: "cm²",
      piMode: "3,14",
      hints: ["Area needs the radius squared.", "$r^{2} = 10 \\times 10 = 100$.", "Now 3,14 × 100 — move the comma two places. Units cm²."],
      success: "$A = 3{,}14 \\times 100 = 314$ cm².",
      answer: { value: 314 },
      misconceptions: [{ when: 62.8, say: "That is the circumference ($2\\pi r$). Area uses $r^{2}$: 3,14 × 10 × 10." }, { when: 31.4, say: "That is $\\pi \\times r$. Area needs $r \\times r$ — square it." }],
      bridge: "BR-FR",
    },
    {
      id: "A6-g2",
      type: "numeric",
      prompt: "Radius $r = 14\\,\\text{cm}$. Find the area. Use $\\pi = \\tfrac{22}{7}$.",
      lead: "A =",
      unit: "cm²",
      piMode: "22/7",
      hints: ["$A = \\tfrac{22}{7} \\times 14 \\times 14$.", "Cancel one 14 with the 7: 14 ÷ 7 = 2. Now it is 22 × 2 × 14.", "22 × 2 = 44, then 44 × 14. Units cm²."],
      success: "$\\tfrac{22}{7} \\times 14 \\times 14 = 22 \\times 2 \\times 14 = 616$ cm².",
      answer: { value: 616 },
      misconceptions: [{ when: 88, say: "That is the circumference. Area squares the radius: 14 × 14 appears in the working." }, { when: 44, say: "That is $\\pi \\times r$. You need $\\pi \\times r \\times r$." }],
      bridge: "BR-FD",
    },
  ],
  independent: [
    {
      id: "A6-i1",
      type: "numeric",
      prompt: "Radius $r = 7\\,\\text{cm}$. Find the area. Use $\\pi = \\tfrac{22}{7}$.",
      lead: "A =",
      unit: "cm²",
      piMode: "22/7",
      hints: ["$A = \\pi r^{2}$.", "$\\tfrac{22}{7} \\times 7 \\times 7$ — cancel one 7.", "22 × 7."],
      success: "$\\tfrac{22}{7} \\times 7 \\times 7 = 22 \\times 7 = 154$ cm².",
      answer: { value: 154 },
      misconceptions: [{ when: 44, say: "That is the circumference $2\\pi r$. Area needs $r^{2}$." }, { when: 22, say: "That is $\\pi \\times r$. Multiply by r once more." }],
      bridge: "BR-FD",
    },
    {
      id: "A6-i2",
      type: "numeric",
      prompt: "A circle has **diameter** $20\\,\\text{cm}$. Find the area. Use $\\pi = 3{,}14$.",
      lead: "A =",
      unit: "cm²",
      piMode: "3,14",
      hints: ["Area wants the radius — you were given a diameter.", "r = 20 ÷ 2 = 10. Now square it.", "3,14 × 100."],
      success: "$r = 10$, so $A = 3{,}14 \\times 10 \\times 10 = 314$ cm².",
      answer: { value: 314 },
      misconceptions: [{ when: 1256, say: "You squared the **diameter**. Area uses the radius: r = 20 ÷ 2 = 10." }, { when: 62.8, say: "That is the circumference $\\pi d$. Area is $\\pi r^{2}$." }],
      bridge: "BR-FR",
    },
    {
      id: "A6-i3",
      type: "mcq",
      prompt: "Which expression gives the **area** of a circle with radius $r$?",
      options: ["$2 \\times \\pi \\times r$", "$\\pi \\times r \\times r$", "$\\pi \\times 2r$", "$2 \\times r \\times r$"],
      correctIndex: 1,
      hints: ["Area is measured in square units — something must be multiplied by itself.", "$r^{2}$ means $r \\times r$.", "Put π in front of $r \\times r$."],
      success: "$\\pi \\times r \\times r = \\pi r^{2}$. The other three are circumference or have no π at all.",
      misconceptions: [{ when: "0", say: "$2\\pi r$ is the circumference — a length, not an area." }, { when: "3", say: "No π there — every circle formula needs π." }],
    },
  ],
  transfer: [
    {
      id: "A6-t1",
      type: "numeric",
      prompt: "A circular light-garden has **diameter** $14\\,\\text{m}$. How much ground does it cover? Use $\\pi = \\tfrac{22}{7}$.",
      plain: "Find the area of a circle with diameter fourteen metres.",
      lead: "A =",
      unit: "m²",
      piMode: "22/7",
      hints: ["“How much ground” is area. Do you have the radius?", "r = 14 ÷ 2 = 7. Then $A = \\tfrac{22}{7} \\times 7 \\times 7$.", "Cancel one 7: 22 × 7. Units m²."],
      success: "$r = 7$ m, so $A = \\tfrac{22}{7} \\times 7 \\times 7 = 154$ m².",
      answer: { value: 154 },
      misconceptions: [{ when: 616, say: "You used 14 as the radius — but 14 is the diameter. Halve it first." }, { when: 44, say: "That is the circumference. “Ground covered” is area." }],
      visual: { kind: "garden", label: "d = 14 m" },
    },
  ],
  recap: {
    headline: "The inside of the circle is lit",
    tutor: "You kept two habits every time — radius, not diameter; squared, not doubled — and the answers followed.",
    bullets: ["Area is the space inside: $A = \\pi r^{2}$, in **square units**.", "Always use the **radius** — halve a diameter first.", "**Square** the radius ($r \\times r$); don’t double it."],
    nextPath: "Next (A7): half a circle — semicircle perimeter and area, including answers left in terms of π.",
    collectible: { name: "Disc bead", glyph: "●", blurb: "Radius, squared, times π." },
  },
};

/* ------------------------------------------------------------------ */
/* A7 — Semicircles                                                    */
/* ------------------------------------------------------------------ */

export const A7: Lesson = {
  id: "A7",
  code: "A7",
  track: "A",
  kind: "core",
  title: "Circles · A7 Semicircles",
  short: "Semicircle",
  minutes: 13,
  piMode: "both",
  prereqs: ["A4", "A6"],
  citations: [
    { file: P2024, page: 3, note: "semicircle area in terms of π" },
    { file: P2024, page: 4, note: "semicircle perimeter, π = 22/7" },
    { file: FOCUS, page: 4, note: "semicircle perimeter in terms of π" },
    { file: P2025AUG, page: 3, note: "semicircle area, π = 3,14" },
  ],
  intro: "About 13 minutes. Half a circle brings one trap: the **perimeter** of a semicircle is half the circumference **plus the straight diameter**. The area is simply half.",
  introBullets: ["Warm-up: a full circumference; halving", "Today: semicircle perimeter and area — and leaving answers in terms of π", "Skill path: A7 · one complete teaching loop"],
  recall: [
    {
      id: "A7-r1",
      type: "numeric",
      prompt: "Full circle, diameter $10\\,\\text{cm}$, $\\pi = 3{,}14$. Circumference?",
      lead: "C =",
      unit: "cm",
      piMode: "3,14",
      hints: ["Diameter → $\\pi d$.", "3,14 × 10.", "Move the comma one place."],
      success: "$C = 31{,}4$ cm.",
      answer: { value: 31.4 },
    },
    {
      id: "A7-r2",
      type: "numeric",
      prompt: "Half of $78{,}5$?",
      hints: ["Halve 78 and halve 0,5 separately.", "39 and 0,25.", "Put them together."],
      success: "$78{,}5 \\div 2 = 39{,}25$.",
      answer: { value: 39.25 },
    },
  ],
  goal: {
    statement: "Today you will find the perimeter and area of a semicircle — and leave an answer in terms of π when asked.",
    tutor: "Cut a circle in half. The area halves. But the perimeter is the curved half **plus** the straight cut — the diameter. Forgetting the straight edge is the classic slip, so we name it now.",
    formula: "P = \\tfrac{1}{2}\\pi d + d \\qquad A = \\tfrac{1}{2}\\pi r^{2}",
    formulaPlain: "Perimeter of a semicircle: half of pi d, plus d. Area: half of pi r squared.",
    visual: { kind: "semicircle", label: "d", shade: true },
    visualTitle: "Visual · half the circle, plus the straight edge",
    after: "“In terms of π” means stop before replacing π with a number: write $18\\pi$, not 56,52.",
  },
  worked: {
    tutor: "I’ll do perimeter and area for the same semicircle, so you can see where they part ways.",
    problem: "A semicircle has diameter $20\\,\\text{cm}$. Find its perimeter and its area. Use $\\pi = 3{,}14$.",
    steps: [
      { title: "Curved part — half the circumference", latex: "\\tfrac{1}{2} \\times 3{,}14 \\times 20 = 31{,}4\\,\\text{cm}" },
      { title: "Perimeter — add the straight diameter", latex: "P = 31{,}4 + 20 = 51{,}4\\,\\text{cm}", note: "The cut edge is part of the boundary." },
      { title: "Area — radius first", latex: "r = 20 \\div 2 = 10", note: "Area always wants r." },
      { title: "Area — half of πr²", latex: "A = \\tfrac{1}{2} \\times 3{,}14 \\times 10^{2} = \\tfrac{1}{2} \\times 314 = 157\\,\\text{cm}^{2}" },
    ],
    why: "Perimeter = arc + diameter. Area = half the full area. Two different halves — one has a straight edge added.",
    visual: { kind: "semicircle", label: "d = 20 cm", shade: true },
  },
  guided: [
    {
      id: "A7-g1",
      type: "numeric",
      prompt: "A semicircle has diameter $14\\,\\text{cm}$. Find its **perimeter**. Use $\\pi = \\tfrac{22}{7}$.",
      lead: "P =",
      unit: "cm",
      piMode: "22/7",
      hints: ["Perimeter = curved part + straight diameter.", "Curved part = ½ × $\\tfrac{22}{7}$ × 14 = ½ × 44.", "Add the straight 14 cm to the curved part."],
      success: "Curved part $= \\tfrac{1}{2} \\times 44 = 22$; perimeter $= 22 + 14 = 36$ cm.",
      answer: { value: 36 },
      misconceptions: [{ when: 22, say: "That is the curved part only. A semicircle’s boundary also has the straight diameter — add 14." }, { when: 44, say: "That is a **full** circle’s circumference. Halve it, then add the diameter." }],
      bridge: "BR-FD",
    },
    {
      id: "A7-g2",
      type: "numeric",
      prompt: "A semicircle has radius $4\\,\\text{cm}$. Find its **area**. Use $\\pi = 3{,}14$.",
      lead: "A =",
      unit: "cm²",
      piMode: "3,14",
      hints: ["Full circle area first: $\\pi r^{2}$.", "$3{,}14 \\times 4 \\times 4 = 3{,}14 \\times 16$.", "Then halve that for the semicircle. Units cm²."],
      success: "Full circle $= 3{,}14 \\times 16 = 50{,}24$; half $= 25{,}12$ cm².",
      answer: { value: 25.12 },
      misconceptions: [{ when: 50.24, say: "That is the full circle. A semicircle is half — divide by 2." }, { when: 12.56, say: "That is $\\pi \\times r$ — you need $r^{2} = 16$ before halving." }],
      bridge: "BR-FR",
    },
  ],
  independent: [
    {
      id: "A7-i1",
      type: "numeric",
      prompt: "A semicircle has radius $6\\,\\text{cm}$. Write its **area in terms of π**.",
      plain: "Give the area as a number times pi, without replacing pi by a decimal.",
      lead: "A =",
      unit: "cm²",
      piMode: "none",
      hints: ["Area of a full circle in terms of π: $\\pi r^{2} = \\pi \\times 36 = 36\\pi$.", "Halve the 36, keep the π.", "Write it as a number followed by π."],
      success: "$A = \\tfrac{1}{2} \\times 36\\pi = 18\\pi$ cm². “In terms of π” means the π stays as a symbol.",
      answer: { value: 18 * Math.PI, tolerance: 0.001, acceptAlso: ["18π", "18 π", "18pi", "18\\pi", "18×π", "π×18", "π18"] },
      misconceptions: [{ when: 56.52, say: "You replaced π with 3,14 — this question wants the answer **in terms of π**, so write 18π." }, { when: 36 * Math.PI, say: "That is the full circle, $36\\pi$. Halve it." }],
    },
    {
      id: "A7-i2",
      type: "numeric",
      prompt: "A semicircle has diameter $28\\,\\text{cm}$. Find its perimeter. Use $\\pi = \\tfrac{22}{7}$.",
      lead: "P =",
      unit: "cm",
      piMode: "22/7",
      hints: ["Arc + diameter.", "Arc = ½ × $\\tfrac{22}{7}$ × 28 = ½ × 88.", "Add 28."],
      success: "Arc $= 44$; perimeter $= 44 + 28 = 72$ cm.",
      answer: { value: 72 },
      misconceptions: [{ when: 44, say: "Arc only — add the straight diameter." }, { when: 88, say: "That is the whole circumference; a semicircle has half the arc, plus the diameter." }],
      bridge: "BR-FD",
    },
    {
      id: "A7-i3",
      type: "mcq",
      prompt: "The **perimeter** of a semicircle is made of…",
      options: ["Half the circumference only", "Half the circumference plus the diameter", "Half the circumference plus the radius", "The full circumference"],
      correctIndex: 1,
      hints: ["Trace the boundary with your finger: curved part, then…?", "The straight cut edge is the full width of the circle.", "Full width = diameter."],
      success: "Half the circumference **plus the diameter** — the straight cut is part of the boundary.",
      misconceptions: [{ when: "2", say: "The straight edge spans the whole circle — that is a diameter, not a radius." }],
    },
  ],
  transfer: [
    {
      id: "A7-t1",
      type: "numeric",
      prompt: "A semicircular window has radius $1\\,\\text{m}$. Wooden trim runs around its **whole** edge. How much trim is needed? Use $\\pi = 3{,}14$.",
      plain: "Find the perimeter of a semicircle with radius one metre.",
      lead: "trim =",
      unit: "m",
      hints: ["Whole edge = curved part + straight bottom.", "Curved part = ½ × 2 × 3,14 × 1 = 3,14. The straight bottom is the diameter = 2 m.", "Add them."],
      success: "Arc $= 3{,}14$ m; plus diameter $2$ m; trim $= 5{,}14$ m.",
      answer: { value: 5.14 },
      misconceptions: [{ when: 3.14, say: "That is the curve only — the trim also runs along the straight bottom (2 m)." }, { when: 4.14, say: "You added the radius (1 m). The straight bottom is the diameter, 2 m." }],
    },
  ],
  recap: {
    headline: "Half a circle, fully understood",
    tutor: "You separated the two halves — area simply halves, perimeter keeps its straight edge — and you left π as a symbol when asked.",
    bullets: ["Semicircle **perimeter** = half the circumference **+ the diameter**.", "Semicircle **area** = half of $\\pi r^{2}$.", "“In terms of π” → keep π as a symbol, e.g. $18\\pi$."],
    nextPath: "Next (A8): quarter circles — a quarter of the arc plus **two** radii.",
    collectible: { name: "Half-moon bead", glyph: "◗", blurb: "Curve plus the straight edge." },
  },
};

/* ------------------------------------------------------------------ */
/* A8 — Quarter circles                                                */
/* ------------------------------------------------------------------ */

export const A8: Lesson = {
  id: "A8",
  code: "A8",
  track: "A",
  kind: "core",
  title: "Circles · A8 Quarter circles",
  short: "Quarter circle",
  minutes: 13,
  piMode: "both",
  prereqs: ["A7"],
  citations: [
    { file: P2025AUG, page: 3, note: "quarter-circle perimeter, π = 22/7" },
    { file: FOCUS, page: 4, note: "quarter-circle border perimeter, π = 3,14" },
  ],
  intro: "About 13 minutes. A quarter circle has a quarter of the arc and **two** straight radii on its boundary. Area is a quarter of the full circle.",
  introBullets: ["Warm-up: quartering; a semicircle arc", "Today: perimeter and area of a quarter circle", "Skill path: A8 · one complete teaching loop"],
  recall: [
    {
      id: "A8-r1",
      type: "numeric",
      prompt: "A quarter of $44$?",
      hints: ["A quarter is half of a half.", "Half of 44 is 22.", "Half of 22."],
      success: "$44 \\div 4 = 11$.",
      answer: { value: 11 },
    },
    {
      id: "A8-r2",
      type: "numeric",
      prompt: "Curved part of a semicircle with diameter $20\\,\\text{cm}$, $\\pi = 3{,}14$?",
      lead: "arc =",
      unit: "cm",
      piMode: "3,14",
      hints: ["Half the full circumference.", "Full: 3,14 × 20 = 62,8.", "Halve it."],
      success: "$\\tfrac{1}{2} \\times 62{,}8 = 31{,}4$ cm.",
      answer: { value: 31.4 },
    },
  ],
  goal: {
    statement: "Today you will find the perimeter and area of a quarter circle.",
    tutor: "Fold a circle in half, then in half again: a quarter. Its boundary is a quarter of the arc plus **two radii** — one on each straight side. Its area is a quarter of the whole.",
    formula: "P = \\tfrac{1}{4}(2\\pi r) + 2r \\qquad A = \\tfrac{1}{4}\\pi r^{2}",
    formulaPlain: "Perimeter: a quarter of two pi r, plus two radii. Area: a quarter of pi r squared.",
    visual: { kind: "quarter", label: "r", shade: true },
    visualTitle: "Visual · quarter arc and two radii",
    after: "Count the straight edges before you add: a semicircle has **one** (the diameter); a quarter circle has **two** (both radii).",
  },
  worked: {
    tutor: "Same rhythm as A7: arc first, straight edges second, area separately.",
    problem: "A quarter circle has radius $14\\,\\text{cm}$. Find its perimeter and area. Use $\\pi = \\tfrac{22}{7}$.",
    steps: [
      { title: "Full circumference, cancelling the 7", latex: "2 \\times \\tfrac{22}{7} \\times 14 = 88" },
      { title: "Quarter of the arc", latex: "\\tfrac{1}{4} \\times 88 = 22\\,\\text{cm}" },
      { title: "Perimeter — add two radii", latex: "P = 22 + 14 + 14 = 50\\,\\text{cm}" },
      { title: "Area — a quarter of πr²", latex: "A = \\tfrac{1}{4} \\times \\tfrac{22}{7} \\times 14 \\times 14 = \\tfrac{1}{4} \\times 616 = 154\\,\\text{cm}^{2}" },
    ],
    why: "Arc = a quarter of the circumference. Perimeter adds **two** radii. Area = a quarter of the full area.",
    visual: { kind: "quarter", label: "r = 14 cm", shade: true },
  },
  guided: [
    {
      id: "A8-g1",
      type: "numeric",
      prompt: "A quarter circle has radius $7\\,\\text{cm}$. Find its **perimeter**. Use $\\pi = \\tfrac{22}{7}$.",
      lead: "P =",
      unit: "cm",
      piMode: "22/7",
      hints: ["Full circumference first: $2 \\times \\tfrac{22}{7} \\times 7 = 44$.", "Quarter of the arc: 44 ÷ 4.", "Add two radii: 7 + 7."],
      success: "Arc $= 44 \\div 4 = 11$; perimeter $= 11 + 7 + 7 = 25$ cm.",
      answer: { value: 25 },
      misconceptions: [{ when: 11, say: "Arc only. A quarter circle also has two straight radii on its edge — add 7 + 7." }, { when: 18, say: "You added one radius. A quarter circle has **two** straight sides." }],
      bridge: "BR-FD",
    },
    {
      id: "A8-g2",
      type: "numeric",
      prompt: "A quarter circle has radius $10\\,\\text{cm}$. Find its **area**. Use $\\pi = 3{,}14$.",
      lead: "A =",
      unit: "cm²",
      piMode: "3,14",
      hints: ["Full circle area: $3{,}14 \\times 10 \\times 10$.", "That is 314. A quarter circle is a quarter of it.", "314 ÷ 4 — halve, then halve again. Units cm²."],
      success: "Full $= 314$; quarter $= 78{,}5$ cm².",
      answer: { value: 78.5 },
      misconceptions: [{ when: 314, say: "That is the full circle — take a quarter." }, { when: 157, say: "That is half. A quarter circle needs one more halving." }],
      bridge: "BR-FR",
    },
  ],
  independent: [
    {
      id: "A8-i1",
      type: "numeric",
      prompt: "A quarter-circle flower bed has radius $4\\,\\text{m}$. Find the perimeter of its border. Use $\\pi = 3{,}14$.",
      lead: "P =",
      unit: "m",
      piMode: "3,14",
      hints: ["Full circumference: 2 × 3,14 × 4 = 25,12.", "Quarter of the arc: 25,12 ÷ 4.", "Add two radii: 4 + 4."],
      success: "Arc $= 25{,}12 \\div 4 = 6{,}28$; perimeter $= 6{,}28 + 8 = 14{,}28$ m.",
      answer: { value: 14.28 },
      misconceptions: [{ when: 6.28, say: "Arc only — add the two straight radii (8 m)." }, { when: 10.28, say: "One radius added; a quarter circle has two straight edges." }],
    },
    {
      id: "A8-i2",
      type: "numeric",
      prompt: "A quarter circle has radius $21\\,\\text{cm}$. Find its area. Use $\\pi = \\tfrac{22}{7}$.",
      lead: "A =",
      unit: "cm²",
      piMode: "22/7",
      hints: ["Full area: $\\tfrac{22}{7} \\times 21 \\times 21$. Cancel one 21 with the 7 → 22 × 3 × 21.", "22 × 3 = 66, then 66 × 21 = 1386.", "Quarter: 1386 ÷ 4. A comma decimal is fine."],
      success: "Full $= 22 \\times 3 \\times 21 = 1386$; quarter $= 346{,}5$ cm².",
      answer: { value: 346.5 },
      misconceptions: [{ when: 1386, say: "Full circle — take a quarter." }, { when: 693, say: "That is half; halve once more." }],
      bridge: "BR-FD",
    },
    {
      id: "A8-i3",
      type: "mcq",
      prompt: "What fraction of a full circle’s **area** is a quarter circle?",
      options: ["$\\tfrac{1}{2}$", "$\\tfrac{1}{3}$", "$\\tfrac{1}{4}$", "$\\tfrac{3}{4}$"],
      correctIndex: 2,
      hints: ["Fold a circle in half, then in half again.", "Two halvings.", "Half of a half."],
      success: "A **quarter** — the same fraction applies to the arc, but the perimeter also adds two radii.",
    },
  ],
  transfer: [
    {
      id: "A8-t1",
      type: "numeric",
      prompt: "A quarter-circle garden bed has radius $6\\,\\text{m}$. A fence runs along its **whole** edge. How long is the fence? Use $\\pi = 3{,}14$.",
      plain: "Find the perimeter of a quarter circle with radius six metres.",
      lead: "fence =",
      unit: "m",
      hints: ["Whole edge = quarter arc + two radii.", "Full circumference: 2 × 3,14 × 6 = 37,68. Quarter: 37,68 ÷ 4.", "Then add 6 + 6."],
      success: "Arc $= 37{,}68 \\div 4 = 9{,}42$; fence $= 9{,}42 + 12 = 21{,}42$ m.",
      answer: { value: 21.42 },
      misconceptions: [{ when: 9.42, say: "That is the curved part only. The fence also runs along both straight sides." }, { when: 15.42, say: "One radius added; a quarter circle has two." }],
    },
  ],
  recap: {
    headline: "The TEXT-CLEAR circle path is complete",
    tutor: "From naming parts to quarter circles — you now hold every circle skill the Herzlia papers test in text-clear form.",
    bullets: ["Quarter-circle **arc** = a quarter of the circumference.", "Quarter-circle **perimeter** adds **two radii**.", "Quarter-circle **area** = a quarter of $\\pi r^{2}$."],
    nextPath: "Composite figures (circle + polygon) come later — they combine exactly these pieces.",
    collectible: { name: "Quarter bead", glyph: "◔", blurb: "An arc and two radii." },
  },
};

export const CIRCLES: Lesson[] = [A1, A2, A3, A4, A5, A6, A7, A8];
