import type { Lesson } from "../types";
import { P2024, P2025AUG } from "../sources";

export const B1: Lesson = {
  id: "B1",
  code: "B1",
  track: "B",
  kind: "core",
  title: "Perimeter & area · B1 Perimeter of squares and rectangles",
  short: "Perimeter · square/rect",
  minutes: 10,
  piMode: "none",
  prereqs: [],
  citations: [{ file: P2025AUG, page: 2, note: "perimeter of a square" }],
  intro: "About 10 minutes. Perimeter is the walk around the edge. For a square that is four equal sides; for a rectangle, two lengths and two breadths.",
  introBullets: ["Warm-up: adding four numbers", "Today: perimeter of squares and rectangles", "Skill path: B1 · one complete teaching loop"],
  recall: [
    {
      id: "B1-r1",
      type: "numeric",
      prompt: "$6 + 6 + 6 + 6 = \\;?$",
      hints: ["Four sixes.", "That is 4 × 6.", "24."],
      success: "$24$ — four equal sides add like a multiplication.",
      answer: { value: 24 },
    },
    {
      id: "B1-r2",
      type: "mcq",
      prompt: "Perimeter is…",
      options: ["The space inside a shape", "The distance around the edge of a shape", "The longest side", "Half the area"],
      correctIndex: 1,
      hints: ["Peri- means around.", "Think of a fence around a field.", "Add up the edges."],
      success: "The distance **around** — add every edge.",
    },
  ],
  goal: {
    statement: "Today you will find the perimeter of a square and of a rectangle.",
    tutor: "Imagine walking the fence line. A square: four identical walks. A rectangle: two long walks and two short ones.",
    formula: "P_{\\square} = 4s \\qquad P_{\\text{rect}} = 2(l + b)",
    formulaPlain: "Square perimeter is four times the side. Rectangle perimeter is two times (length plus breadth).",
    visual: { kind: "rectangle", w: "l", h: "b" },
    visualTitle: "Visual · walking the edge",
    after: "Units stay as lengths: cm, m — never squared.",
  },
  worked: {
    tutor: "Both shapes, same idea — add every side.",
    problem: "(a) A square has side $9\\,\\text{cm}$. (b) A rectangle is $7\\,\\text{cm}$ by $4\\,\\text{cm}$. Find each perimeter.",
    steps: [
      { title: "(a) Four equal sides", latex: "P = 4 \\times 9 = 36\\,\\text{cm}" },
      { title: "(b) Length plus breadth", latex: "7 + 4 = 11" },
      { title: "(b) Two of each", latex: "P = 2 \\times 11 = 22\\,\\text{cm}" },
    ],
    why: "Perimeter adds lengths, so the unit is cm — not cm².",
    visual: { kind: "rectangle", w: "7 cm", h: "4 cm" },
  },
  guided: [
    {
      id: "B1-g1",
      type: "numeric",
      prompt: "A square has side $12\\,\\text{cm}$. Perimeter?",
      lead: "P =",
      unit: "cm",
      hints: ["Four equal sides.", "4 × 12.", "48."],
      success: "$4 \\times 12 = 48$ cm.",
      answer: { value: 48 },
      misconceptions: [{ when: 144, say: "12 × 12 is the **area**. Perimeter adds four sides: 4 × 12." }],
      bridge: "BR-FR",
    },
    {
      id: "B1-g2",
      type: "numeric",
      prompt: "A rectangle is $15\\,\\text{m}$ long and $6\\,\\text{m}$ wide. Perimeter?",
      lead: "P =",
      unit: "m",
      hints: ["Two lengths, two widths.", "2 × (15 + 6).", "2 × 21."],
      success: "$2(15 + 6) = 42$ m.",
      answer: { value: 42 },
      misconceptions: [{ when: 90, say: "15 × 6 is the area. Add the sides instead." }, { when: 21, say: "That is one length plus one width — a rectangle has two of each." }],
      bridge: "BR-FR",
    },
  ],
  independent: [
    {
      id: "B1-i1",
      type: "numeric",
      prompt: "A square has side $7{,}5\\,\\text{cm}$. Perimeter?",
      lead: "P =",
      unit: "cm",
      hints: ["4 × 7,5.", "4 × 7 = 28 and 4 × 0,5 = 2.", "Add them."],
      success: "$4 \\times 7{,}5 = 30$ cm.",
      answer: { value: 30 },
    },
    {
      id: "B1-i2",
      type: "numeric",
      prompt: "A rectangle is $20\\,\\text{cm}$ by $8\\,\\text{cm}$. Perimeter?",
      lead: "P =",
      unit: "cm",
      hints: ["2 × (20 + 8).", "20 + 8 = 28.", "Double it."],
      success: "$2 \\times 28 = 56$ cm.",
      answer: { value: 56 },
      misconceptions: [{ when: 160, say: "20 × 8 is area. Perimeter adds edges." }],
    },
    {
      id: "B1-i3",
      type: "mcq",
      prompt: "A square has perimeter $32\\,\\text{cm}$. How long is one side?",
      options: ["4 cm", "8 cm", "16 cm", "128 cm"],
      correctIndex: 1,
      hints: ["Four equal sides make 32.", "32 ÷ 4.", "8."],
      success: "$32 \\div 4 = 8$ cm — working backwards from the perimeter.",
    },
  ],
  transfer: [
    {
      id: "B1-t1",
      type: "numeric",
      prompt: "A rectangular light-garden is $11\\,\\text{m}$ by $5\\,\\text{m}$. A lantern-rope runs once around its edge. How long is the rope?",
      lead: "rope =",
      unit: "m",
      hints: ["Once around = perimeter.", "2 × (11 + 5).", "2 × 16."],
      success: "$2(11 + 5) = 32$ m of rope.",
      answer: { value: 32 },
      misconceptions: [{ when: 55, say: "11 × 5 covers the ground (area). The rope goes around the edge." }],
    },
  ],
  recap: {
    headline: "The fence line is measured",
    tutor: "You added edges — and each time you noticed when a slip had turned into area instead.",
    bullets: ["Perimeter = distance **around**; add every side.", "Square: $P = 4s$. Rectangle: $P = 2(l + b)$.", "Units stay as lengths (cm, m)."],
    nextPath: "Next (B2): area of a rectangle — covering the inside in square units.",
    collectible: { name: "Fence bead", glyph: "▭", blurb: "Around the edge." },
  },
};

export const B2: Lesson = {
  id: "B2",
  code: "B2",
  track: "B",
  kind: "core",
  title: "Perimeter & area · B2 Area of rectangles",
  short: "Area · rectangle",
  minutes: 10,
  piMode: "none",
  prereqs: ["B1"],
  citations: [{ file: P2025AUG, page: 2, note: "area of a rectangle" }],
  intro: "About 10 minutes. Area is how many unit squares cover the inside. For a rectangle, rows × columns — length × breadth.",
  introBullets: ["Warm-up: perimeter vs area", "Today: area of rectangles and squares", "Skill path: B2 · one complete teaching loop"],
  recall: [
    {
      id: "B2-r1",
      type: "mcq",
      prompt: "Which one is measured in **square** units?",
      options: ["Perimeter", "Area", "Length", "Height"],
      correctIndex: 1,
      hints: ["Which covers space?", "Squares tile a surface.", "cm²."],
      success: "Area — cm², m².",
    },
    {
      id: "B2-r2",
      type: "numeric",
      prompt: "A rectangle is $6$ by $4$. Perimeter?",
      lead: "P =",
      hints: ["2 × (6 + 4).", "2 × 10.", "20."],
      success: "$20$ — keep that in mind; the area will be different.",
      answer: { value: 20 },
    },
  ],
  goal: {
    statement: "Today you will find the area of a rectangle using $A = l \\times b$.",
    tutor: "Picture a grid of 1 cm squares filling the rectangle: 6 across, 4 down → 6 × 4 = 24 squares. That count **is** the area.",
    formula: "A = l \\times b \\qquad A_{\\square} = s \\times s = s^{2}",
    formulaPlain: "Area equals length times breadth. A square’s area is side squared.",
    visual: { kind: "rectangle", w: "6 cm", h: "4 cm", shade: true },
    visualTitle: "Visual · unit squares filling the inside",
    after: "Write the unit squared: **cm²**. Even when a paper prints “cm” by mistake, area is always square units.",
  },
  worked: {
    tutor: "Same rectangle as the warm-up — see how area and perimeter give different numbers and different units.",
    problem: "A rectangle is $8\\,\\text{cm}$ by $5\\,\\text{cm}$. Find its area.",
    steps: [
      { title: "Formula", latex: "A = l \\times b" },
      { title: "Substitute", latex: "A = 8 \\times 5" },
      { title: "Calculate with square units", latex: "A = 40\\,\\text{cm}^{2}", note: "Perimeter would be 26 cm — different number, different unit." },
    ],
    why: "Area multiplies two lengths, so the unit is cm × cm = cm².",
    visual: { kind: "rectangle", w: "8 cm", h: "5 cm", shade: true },
  },
  guided: [
    {
      id: "B2-g1",
      type: "numeric",
      prompt: "A rectangle is $9\\,\\text{cm}$ by $6\\,\\text{cm}$. Area?",
      lead: "A =",
      unit: "cm²",
      hints: ["Length × breadth.", "9 × 6.", "54, in cm²."],
      success: "$9 \\times 6 = 54$ cm².",
      answer: { value: 54 },
      misconceptions: [{ when: 30, say: "2(9 + 6) = 30 is the perimeter. Area multiplies: 9 × 6." }],
      bridge: "BR-FR",
    },
    {
      id: "B2-g2",
      type: "numeric",
      prompt: "A square has side $7\\,\\text{m}$. Area?",
      lead: "A =",
      unit: "m²",
      hints: ["Side × side.", "7 × 7.", "49 m²."],
      success: "$7 \\times 7 = 49$ m².",
      answer: { value: 49 },
      misconceptions: [{ when: 28, say: "4 × 7 = 28 is the perimeter. Area is 7 × 7." }, { when: 14, say: "7 × 2 is doubling. Area squares: 7 × 7." }],
      bridge: "BR-FR",
    },
  ],
  independent: [
    {
      id: "B2-i1",
      type: "numeric",
      prompt: "A rectangle is $12\\,\\text{cm}$ by $3{,}5\\,\\text{cm}$. Area?",
      lead: "A =",
      unit: "cm²",
      hints: ["12 × 3,5.", "12 × 3 = 36 and 12 × 0,5 = 6.", "Add them."],
      success: "$12 \\times 3{,}5 = 42$ cm².",
      answer: { value: 42 },
      misconceptions: [{ when: 31, say: "That is the perimeter. Multiply for area." }],
    },
    {
      id: "B2-i2",
      type: "numeric",
      prompt: "A rectangle has area $48\\,\\text{cm}^{2}$ and length $8\\,\\text{cm}$. What is its breadth?",
      lead: "b =",
      unit: "cm",
      hints: ["A = l × b, so b = A ÷ l.", "48 ÷ 8.", "6."],
      success: "$48 \\div 8 = 6$ cm.",
      answer: { value: 6 },
      misconceptions: [{ when: 384, say: "You multiplied. To find a missing side, divide the area by the known side." }],
    },
    {
      id: "B2-i3",
      type: "mcq",
      prompt: "Which unit is correct for the **area** of a rectangle measured in metres?",
      options: ["m", "m²", "m³", "cm"],
      correctIndex: 1,
      hints: ["Area = two lengths multiplied.", "m × m.", "Square metres."],
      success: "m² — square metres.",
    },
  ],
  transfer: [
    {
      id: "B2-t1",
      type: "numeric",
      prompt: "A rectangular light-garden is $11\\,\\text{m}$ by $5\\,\\text{m}$. How much ground does it cover?",
      lead: "A =",
      unit: "m²",
      hints: ["Ground covered = area.", "11 × 5.", "55 m²."],
      success: "$11 \\times 5 = 55$ m² — compare the 32 m of rope around it in B1.",
      answer: { value: 55 },
      misconceptions: [{ when: 32, say: "32 m is the perimeter (the rope). Ground covered is area: 11 × 5." }],
    },
  ],
  recap: {
    headline: "The inside is measured",
    tutor: "You separated area from perimeter every time — different number, different unit.",
    bullets: ["Area of a rectangle: $A = l \\times b$; square: $s^{2}$.", "Units are **squared**: cm², m².", "Missing side → divide the area by the known side."],
    nextPath: "Next (B3): triangles — half of base × height, even when the height is drawn outside.",
    collectible: { name: "Tile bead", glyph: "▦", blurb: "Covering the inside." },
  },
};

export const B3: Lesson = {
  id: "B3",
  code: "B3",
  track: "B",
  kind: "core",
  title: "Perimeter & area · B3 Area of a triangle",
  short: "Area · triangle",
  minutes: 11,
  piMode: "none",
  prereqs: ["B2"],
  citations: [
    { file: P2024, page: 3, note: "triangle area with external height" },
    { file: P2025AUG, page: 4, note: "triangle area with external height" },
  ],
  intro: "About 11 minutes. A triangle is half a rectangle — so its area is half of base × height. The height must be **perpendicular** to the base, even if it is drawn outside the triangle.",
  introBullets: ["Warm-up: rectangle area; halving", "Today: area of a triangle, including an external height", "Skill path: B3 · one complete teaching loop"],
  recall: [
    {
      id: "B3-r1",
      type: "numeric",
      prompt: "A rectangle is $10$ by $6$. Area?",
      lead: "A =",
      hints: ["l × b.", "10 × 6.", "60."],
      success: "$60$.",
      answer: { value: 60 },
    },
    {
      id: "B3-r2",
      type: "numeric",
      prompt: "Half of $60$?",
      hints: ["Divide by 2.", "60 ÷ 2.", "30."],
      success: "$30$ — a triangle inside that rectangle would have this area.",
      answer: { value: 30 },
    },
  ],
  goal: {
    statement: "Today you will find the area of a triangle using $A = \\tfrac{1}{2} \\times \\text{base} \\times \\text{height}$.",
    tutor: "Draw a rectangle around any triangle and it fills exactly half. The height is the perpendicular distance from the base to the top point — for a leaning (obtuse) triangle it lands **outside**, and that is fine.",
    formula: "A = \\tfrac{1}{2} b h",
    formulaPlain: "Area equals half of base times height.",
    visual: { kind: "triangle", base: "b", height: "h", external: true },
    visualTitle: "Visual · half a rectangle, height outside",
    after: "Use the **perpendicular** height (the dotted line with the right-angle mark) — never a slanted side.",
  },
  worked: {
    tutor: "I pick the base and the perpendicular height, ignore the slanted sides, and halve.",
    problem: "A triangle has base $10\\,\\text{cm}$ and perpendicular height $6\\,\\text{cm}$. Find its area.",
    steps: [
      { title: "Formula", latex: "A = \\tfrac{1}{2} \\times b \\times h" },
      { title: "Substitute", latex: "A = \\tfrac{1}{2} \\times 10 \\times 6" },
      { title: "Calculate", latex: "A = \\tfrac{1}{2} \\times 60 = 30\\,\\text{cm}^{2}" },
    ],
    why: "Base × height gives the surrounding rectangle; the triangle is half of it.",
    visual: { kind: "triangle", base: "10 cm", height: "6 cm" },
  },
  guided: [
    {
      id: "B3-g1",
      type: "numeric",
      prompt: "A triangle has base $14\\,\\text{cm}$ and perpendicular height $5\\,\\text{cm}$. Area?",
      lead: "A =",
      unit: "cm²",
      hints: ["½ × b × h.", "14 × 5 = 70.", "Halve it."],
      success: "$\\tfrac{1}{2} \\times 14 \\times 5 = 35$ cm².",
      answer: { value: 35 },
      misconceptions: [{ when: 70, say: "That is base × height — the whole rectangle. A triangle is half." }],
      bridge: "BR-FR",
    },
    {
      id: "B3-g2",
      type: "numeric",
      prompt: "An obtuse triangle has base $8\\,\\text{cm}$. Its perpendicular height, drawn **outside** the triangle, is $5\\,\\text{cm}$. One slanted side is $9\\,\\text{cm}$. Area?",
      lead: "A =",
      unit: "cm²",
      visual: { kind: "triangle", base: "8 cm", height: "5 cm", external: true, side: "9 cm" },
      hints: ["Which two numbers does the formula want — base and **perpendicular** height.", "The 9 cm side is a distractor. Use 8 and 5.", "½ × 8 × 5."],
      success: "$\\tfrac{1}{2} \\times 8 \\times 5 = 20$ cm². The slanted 9 cm side is never used for area.",
      answer: { value: 20 },
      misconceptions: [{ when: 36, say: "You used the slanted 9 cm side. Height must be perpendicular — the 5 cm dotted line." }, { when: 40, say: "That is 8 × 5 without halving." }],
      bridge: "BR-FR",
    },
  ],
  independent: [
    {
      id: "B3-i1",
      type: "numeric",
      prompt: "A triangle has base $12\\,\\text{cm}$ and perpendicular height $7\\,\\text{cm}$. Area?",
      lead: "A =",
      unit: "cm²",
      hints: ["½ × 12 × 7.", "Halve 12 first: 6 × 7.", "42."],
      success: "$6 \\times 7 = 42$ cm².",
      answer: { value: 42 },
      misconceptions: [{ when: 84, say: "Halve it — a triangle is half of base × height." }],
    },
    {
      id: "B3-i2",
      type: "numeric",
      prompt: "A leaning triangle has base $6\\,\\text{m}$, external perpendicular height $9\\,\\text{m}$ and a slanted side of $11\\,\\text{m}$. Area?",
      lead: "A =",
      unit: "m²",
      visual: { kind: "triangle", base: "6 m", height: "9 m", external: true, side: "11 m" },
      hints: ["Base and perpendicular height only.", "½ × 6 × 9.", "3 × 9."],
      success: "$\\tfrac{1}{2} \\times 6 \\times 9 = 27$ m².",
      answer: { value: 27 },
      misconceptions: [{ when: 33, say: "The 11 m slanted side is not the height. Use the perpendicular 9 m." }, { when: 54, say: "Halve it." }],
    },
    {
      id: "B3-i3",
      type: "mcq",
      prompt: "In the area formula for a triangle, the “height” must be…",
      options: ["The longest side", "Any side that isn’t the base", "The perpendicular distance from the base to the opposite vertex", "Half the base"],
      correctIndex: 2,
      hints: ["Look for the right-angle mark.", "Perpendicular means at 90° to the base.", "It may sit outside the triangle."],
      success: "The **perpendicular** distance — marked with a right angle, sometimes outside the triangle.",
    },
  ],
  transfer: [
    {
      id: "B3-t1",
      type: "numeric",
      prompt: "A triangular sail has a bottom edge of $4\\,\\text{m}$ and rises $6\\,\\text{m}$ straight up from it. How much cloth is the sail?",
      lead: "A =",
      unit: "m²",
      hints: ["Cloth = area. Base 4, perpendicular height 6.", "½ × 4 × 6.", "12."],
      success: "$\\tfrac{1}{2} \\times 4 \\times 6 = 12$ m² of cloth.",
      answer: { value: 12 },
      misconceptions: [{ when: 24, say: "Halve — a triangle is half of 4 × 6." }],
    },
  ],
  recap: {
    headline: "Half a rectangle, every time",
    tutor: "You ignored slanted distractors and used the perpendicular height — the exact skill obtuse-triangle items test.",
    bullets: ["Triangle area: $A = \\tfrac{1}{2} b h$.", "Height is **perpendicular** to the base — it may be drawn outside.", "Slanted sides are never the height."],
    nextPath: "Next (B4): a composite — rectangle plus triangle — for perimeter **and** area.",
    collectible: { name: "Sail bead", glyph: "◭", blurb: "Half of base times height." },
  },
};

export const B4: Lesson = {
  id: "B4",
  code: "B4",
  track: "B",
  kind: "core",
  title: "Perimeter & area · B4 A simple composite",
  short: "Composite · rect + triangle",
  minutes: 13,
  piMode: "none",
  prereqs: ["B3"],
  citations: [
    { file: P2025AUG, page: 3, note: "composite perimeter: square + right triangle" },
    { file: P2024, page: 5, note: "composite perimeter and area: rectangle + triangles" },
  ],
  intro: "About 13 minutes. Composite shapes are built from pieces you already know. Area: add the pieces. Perimeter: walk the **outside** only — the shared edge is not on the boundary.",
  introBullets: ["Warm-up: rectangle and triangle area", "Today: perimeter and area of a rectangle + triangle composite", "Skill path: B4 · one complete teaching loop"],
  recall: [
    {
      id: "B4-r1",
      type: "numeric",
      prompt: "Area of a $10\\,\\text{cm}$ by $4\\,\\text{cm}$ rectangle?",
      lead: "A =",
      unit: "cm²",
      hints: ["l × b.", "10 × 4.", "40."],
      success: "$40$ cm².",
      answer: { value: 40 },
      bridge: "BR-FR",
    },
    {
      id: "B4-r2",
      type: "numeric",
      prompt: "Area of a right triangle with legs $4\\,\\text{cm}$ and $3\\,\\text{cm}$?",
      lead: "A =",
      unit: "cm²",
      hints: ["The two legs are base and height.", "½ × 4 × 3.", "6."],
      success: "$\\tfrac{1}{2} \\times 4 \\times 3 = 6$ cm².",
      answer: { value: 6 },
      bridge: "BR-FR",
    },
  ],
  goal: {
    statement: "Today you will find the perimeter and the area of a shape made from a rectangle and a right triangle.",
    tutor: "Our shape: a rectangle 10 cm long and 4 cm tall, with a right triangle glued to its right-hand 4 cm side. The triangle’s other leg is 3 cm and its slanted side is 5 cm. Every length is on the diagram — nothing to guess.",
    formula: "A = A_{\\text{rect}} + A_{\\triangle} \\qquad P = \\text{outside edges only}",
    formulaPlain: "Area is the rectangle area plus the triangle area. Perimeter adds only the outside edges.",
    visual: { kind: "composite-rect-tri" },
    visualTitle: "Visual · rectangle + right triangle",
    after: "The 4 cm edge where the triangle meets the rectangle is **inside** the shape — it is not part of the perimeter.",
  },
  worked: {
    tutor: "Area first (add pieces), then perimeter (walk the outside, skipping the glued edge).",
    problem: "Rectangle $10\\,\\text{cm} \\times 4\\,\\text{cm}$; right triangle attached to the right side with legs $4\\,\\text{cm}$ (shared) and $3\\,\\text{cm}$, hypotenuse $5\\,\\text{cm}$. Find the area and the perimeter.",
    steps: [
      { title: "Area of the rectangle", latex: "10 \\times 4 = 40\\,\\text{cm}^{2}" },
      { title: "Area of the triangle", latex: "\\tfrac{1}{2} \\times 4 \\times 3 = 6\\,\\text{cm}^{2}" },
      { title: "Total area", latex: "A = 40 + 6 = 46\\,\\text{cm}^{2}" },
      { title: "Perimeter — outside edges only", latex: "P = 10 + 4 + 10 + 3 + 5 = 32\\,\\text{cm}", note: "Top 10, left 4, bottom 10, then the triangle’s 3 and 5. The shared 4 cm is skipped." },
    ],
    why: "Area adds every piece. Perimeter traces the boundary — a glued edge is not boundary.",
    visual: { kind: "composite-rect-tri" },
  },
  guided: [
    {
      id: "B4-g1",
      type: "numeric",
      prompt: "Using the diagram: a rectangle $6\\,\\text{cm}$ long and $3\\,\\text{cm}$ tall has a right triangle on its right side with legs $3\\,\\text{cm}$ (shared) and $4\\,\\text{cm}$, hypotenuse $5\\,\\text{cm}$. Find the **area**.",
      lead: "A =",
      unit: "cm²",
      hints: ["Two pieces: rectangle 6 × 3 and triangle ½ × 3 × 4.", "18 and 6.", "Add them."],
      success: "$18 + 6 = 24$ cm².",
      answer: { value: 24 },
      misconceptions: [{ when: 30, say: "You used 3 × 4 for the triangle without halving." }, { when: 18, say: "That is the rectangle only — add the triangle." }],
      bridge: "BR-FR",
    },
    {
      id: "B4-g2",
      type: "numeric",
      prompt: "Same shape. Find the **perimeter**.",
      lead: "P =",
      unit: "cm",
      hints: ["Walk the outside: top 6, left 3, bottom 6, then the triangle’s outer sides.", "The triangle’s outer sides are 4 and 5. The shared 3 cm is inside.", "6 + 3 + 6 + 4 + 5."],
      success: "$6 + 3 + 6 + 4 + 5 = 24$ cm. (Yes — the same number as the area here, but cm not cm².)",
      answer: { value: 24 },
      misconceptions: [{ when: 27, say: "You included the shared 3 cm edge — it is inside the shape, not on the boundary." }, { when: 30, say: "Check: the rectangle’s right side is glued to the triangle, so count it neither for the rectangle nor the triangle." }],
    },
  ],
  independent: [
    {
      id: "B4-i1",
      type: "numeric",
      prompt: "A rectangle $12\\,\\text{cm}$ long and $5\\,\\text{cm}$ tall has a right triangle on its right side with legs $5\\,\\text{cm}$ (shared) and $12\\,\\text{cm}$, hypotenuse $13\\,\\text{cm}$. Find the area.",
      lead: "A =",
      unit: "cm²",
      hints: ["Rectangle: 12 × 5 = 60.", "Triangle: ½ × 5 × 12 = 30.", "Add."],
      success: "$60 + 30 = 90$ cm².",
      answer: { value: 90 },
      misconceptions: [{ when: 120, say: "Triangle needs halving: ½ × 5 × 12 = 30." }],
    },
    {
      id: "B4-i2",
      type: "numeric",
      prompt: "Same shape as above. Find the perimeter.",
      lead: "P =",
      unit: "cm",
      hints: ["Outside edges: 12 (top), 5 (left), 12 (bottom), then the triangle’s 12 and 13.", "Skip the shared 5 cm.", "12 + 5 + 12 + 12 + 13."],
      success: "$12 + 5 + 12 + 12 + 13 = 54$ cm.",
      answer: { value: 54 },
      misconceptions: [{ when: 59, say: "You added the shared 5 cm edge — it is inside." }],
    },
    {
      id: "B4-i3",
      type: "mcq",
      prompt: "When two shapes are joined along an edge, that edge…",
      options: ["Counts twice in the perimeter", "Counts once in the perimeter", "Is not part of the perimeter", "Is added to the area"],
      correctIndex: 2,
      hints: ["Perimeter is the outside boundary.", "Is the glued edge on the outside?", "It is inside — so it is not on the boundary."],
      success: "Not part of the perimeter — it is inside the combined shape.",
    },
  ],
  transfer: [
    {
      id: "B4-t1",
      type: "numeric",
      prompt: "A garden is a $9\\,\\text{m}$ by $4\\,\\text{m}$ rectangle with a right-triangle bed attached to one $4\\,\\text{m}$ side; the bed’s other leg is $3\\,\\text{m}$ and its slanted edge $5\\,\\text{m}$. How much fencing goes around the **whole** garden?",
      lead: "fence =",
      unit: "m",
      hints: ["Fencing = perimeter, outside only.", "9 + 4 + 9, then the triangle’s 3 and 5.", "Skip the shared 4 m."],
      success: "$9 + 4 + 9 + 3 + 5 = 30$ m of fencing.",
      answer: { value: 30 },
      misconceptions: [{ when: 34, say: "The shared 4 m edge is inside the garden — no fence there." }, { when: 42, say: "That is the area (36 + 6). Fencing is perimeter." }],
    },
  ],
  recap: {
    headline: "Pieces joined, boundary traced",
    tutor: "You added pieces for area and skipped the glued edge for perimeter — the two rules every composite question turns on.",
    bullets: ["Composite **area**: add the areas of the pieces.", "Composite **perimeter**: outside edges only — skip shared edges.", "Right triangle: the two legs are base and height."],
    nextPath: "Circle-and-polygon composites come later; they add semicircle and quarter-circle pieces to exactly this method.",
    collectible: { name: "Mosaic bead", glyph: "⬡", blurb: "Pieces into one shape." },
  },
};

export const MEASURE: Lesson[] = [B1, B2, B3, B4];
